<a href="https://colab.research.google.com/github/nedokormysh/Stepik_LLM/blob/week_4_RAG/LLM_4_1_%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D1%87.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ноутбук для решения задач из 4 модуля

In [5]:
!pip install openai langchain tiktoken langchain-openai langchain-community sentence_transformers faiss-cpu pypdf -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.9/362.9 kB 17.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 997.8/997.8 kB 41.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 43.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 62.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.0/27.0 MB 38.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.8/295.8 kB 15.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 318.9/318.9 kB 19.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 391.5/391.5 kB 14.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.9/148.9 kB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.9/141.9 kB 8.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 3.2 MB/s eta 0:00:00

In [6]:
from typing import List

## Если используете ключ от OpenAI, запустите эту ячейку 👇

In [ ]:
from langchain_openai import ChatOpenAI
import os
from getpass import getpass


# os.environ['OPENAI_API_KEY'] = "Введите ваш OpenAI API ключ"
os.environ['OPENAI_API_KEY'] = getpass(prompt='Введите ваш OpenAI API ключ')

# Инициализируем языковую модель
llm = ChatOpenAI(temperature=0.0)

## Если используете ключ из курса, запустите эти ячейки 👇

In [7]:
!wget https://raw.githubusercontent.com/a-milenkin/LLM_practical_course/main/notebooks/utils.py

--2024-08-21 08:19:14--  https://raw.githubusercontent.com/a-milenkin/LLM_practical_course/main/notebooks/utils.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11184 (11K) [text/plain]
Saving to: ‘utils.py’

utils.py            100%[===================>]  10.92K  --.-KB/s    in 0s

2024-08-21 08:19:14 (74.0 MB/s) - ‘utils.py’ saved [11184/11184]

In [8]:
from utils import ChatOpenAI
from getpass import getpass

#course_api_key= "Введите ваш API ключ с курса"
course_api_key = getpass(prompt='Введите API ключ')

# Инициализируем языковую модель
llm = ChatOpenAI(temperature=0.0, course_api_key=course_api_key)

Введите API ключ··········

## Задание 4.1.5 Кастомный Text Splitter

---

# *Напишите функцию*

Задача — написать функцию get_content_from_sections(text: str) -> List[str], которая принимает такой текст в качестве входных данных и возвращает список, содержащий ключевые слова (весь текст) из каждого раздела и подраздела, исключая сами заголовки.

Замечание — Собранный текст с каждого основого раздела (1, 2, 3 и т.д.) поместить в одну строку, разделив пробелами. То есть список на выходе должен иметь длину, равную количеству основных разделов.

In [ ]:
def get_content_from_sections(text: str) -> List[str]:
    # your code here
    return

#Тексты из тестов

In [ ]:

text1 = """
1. Вступление
Описание курса, начальные требования, для кого этот курс.
1.1 Как правильно входить в курс
Цели курса, канал и комьюнити, глоссарий, PET-проект, хард режим vs лайт режим?
1.2 Общий подход и точки улучшения приложений с LLM
Рассказываем почему важно разбираться в LLM. Нужен ли ИИ обычному человеку?
1.3 API ключ курса или от OpenAI?
1.3.1 Ключ от команды курса
Получаем ключ в боте.
1.3.2 Ключ от OpenAI
Получаем официальный ключ от OpenAI.
1.3.3 Ключ от HuggingFace
Ныряем в Open Source и получаем ключ от HuggingFace.
2. Промптинг - объясни LLM, что тебе от неё надо!
2.1 Введение в Prompt Engineering
Поясняем за промпты. Техники и лайфхаки для промптинга. Из чего состоит промпт?
2.2 Дизайн промптов в LangChain
Few-shot learning. Output Parser.
2.2.1 Введение в LangChain
Рассказываем про преимущества LangChain.
3. LangChain или причем тут попугаи?
3.1 Память в LangChain
Переводим LLM в чат-режим. Типы памяти.
3.2 Chains - собери свою цепь
Chains & LCEL.
3.3 Агенты intro
Агенты и цепи. Инструменты (tools).
"""

text2 = """


"""

text3 = """
1. Главный заголовок
Тут содержимое, которое нужно достать из главного заголовка.
1.1 Подзаголовок
Тут содержимое, которое нужно достать из подзаголовка.
"""

text4 = """
1. Первый заголовок

2. Второй заголовок
"""

text5 = """
1. Введение
Краткое описание целей и задач документа.

2. Основные разделы
Краткий обзор основных разделов.

2.1 Первый подраздел
Какие-то мелкие детали.

3. Заключение
Выводы и заключительные комментарии.
4. Приложения
Дополнительная информация и материалы.
"""

In [ ]:
# [
#     "Описание курса, начальные требования, для кого этот курс. Цели курса, канал и комьюнити, глоссарий, PET-проект, хард режим vs лайт режим? Рассказываем почему важно разбираться в LLM. Нужен ли ИИ обычному человеку? Получаем ключ в боте. Получаем официальный ключ от OpenAI. Ныряем в Open Source и получаем ключ от HuggingFace.",
#     "Поясняем за промпты. Техники и лайфхаки для промптинга. Из чего состоит промпт? Few-shot learning. Output Parser. Рассказываем про преимущества LangChain.",
#     "Переводим LLM в чат-режим. Типы памяти. Chains & LCEL. Агенты и цепи. Инструменты (tools)."
]

In [ ]:
import re

In [ ]:
sequence = "Описание курса, начальные требования, для кого этот курс."

In [ ]:
number_pattern = re.compile(r'\d')
# def contains_number(sequence):
#     return bool(number_pattern.search(sequence))
bool(number_pattern.search(sequence))

False

In [ ]:
def get_content_from_sections(text: str) -> List[str]:

    parts = re.split(r'\n{1}.', text)
    print(parts)
    lst = []
    number_pattern = re.compile(r'\d')

    for l in parts:
        if not bool(number_pattern.search(l)):
            lst.append(l)

    return lst

get_content_from_sections(text1)

['', '. Вступление', 'писание курса, начальные требования, для кого этот курс.', '.1 Как правильно входить в курс', 'ели курса, канал и комьюнити, глоссарий, PET-проект, хард режим vs лайт режим?', '.2 Общий подход и точки улучшения приложений с LLM', 'ассказываем почему важно разбираться в LLM. Нужен ли ИИ обычному человеку?', '.3 API ключ курса или от OpenAI?', '.3.1 Ключ от команды курса', 'олучаем ключ в боте.', '.3.2 Ключ от OpenAI', 'олучаем официальный ключ от OpenAI.', '.3.3 Ключ от HuggingFace', 'ыряем в Open Source и получаем ключ от HuggingFace.', '. Промптинг - объясни LLM, что тебе от неё надо!', '.1 Введение в Prompt Engineering', 'оясняем за промпты. Техники и лайфхаки для промптинга. Из чего состоит промпт?', '.2 Дизайн промптов в LangChain', 'ew-shot learning. Output Parser.', '.2.1 Введение в LangChain', 'ассказываем про преимущества LangChain.', '. LangChain или причем тут попугаи?', '.1 Память в LangChain', 'ереводим LLM в чат-режим. Типы памяти.', '.2 Chains - собери свою цепь', 'hains & LCEL.', '.3 Агенты intro', 'генты и цепи. Инструменты (tools).\n']

['',
 '. Вступление',
 'писание курса, начальные требования, для кого этот курс.',
 'ели курса, канал и комьюнити, глоссарий, PET-проект, хард режим vs лайт режим?',
 'ассказываем почему важно разбираться в LLM. Нужен ли ИИ обычному человеку?',
 'олучаем ключ в боте.',
 'олучаем официальный ключ от OpenAI.',
 'ыряем в Open Source и получаем ключ от HuggingFace.',
 '. Промптинг - объясни LLM, что тебе от неё надо!',
 'оясняем за промпты. Техники и лайфхаки для промптинга. Из чего состоит промпт?',
 'ew-shot learning. Output Parser.',
 'ассказываем про преимущества LangChain.',
 '. LangChain или причем тут попугаи?',
 'ереводим LLM в чат-режим. Типы памяти.',
 'hains & LCEL.',
 'генты и цепи. Инструменты (tools).\n']

In [ ]:
import re
from typing import List

def get_content_from_sections(text: str) -> List[str]:
    # Регулярное выражение для поиска заголовков основных разделов
    section_pattern = re.compile(r'^\d+\.\s+.*$', re.MULTILINE)
    # Регулярное выражение для поиска заголовков подразделов
    subsection_pattern = re.compile(r'^\d+\.\d+\.\s+.*$', re.MULTILINE)

    # Разделяем текст на основные разделы
    sections = section_pattern.split(text)

    # print(len(sections))
    # print(sections)

    result = []
    for section in sections:
        if section.strip():

            # Удаляем заголовки подразделов и объединяем текст в одну строку
            section_content = subsection_pattern.sub('', section).strip()
            print(section_content)
            if section_content:
                result.append(section_content)

    # result = [x.split('\n') for x in result]

    return result
r = get_content_from_sections(text1)

Описание курса, начальные требования, для кого этот курс.
1.1 Как правильно входить в курс
Цели курса, канал и комьюнити, глоссарий, PET-проект, хард режим vs лайт режим?
1.2 Общий подход и точки улучшения приложений с LLM
Рассказываем почему важно разбираться в LLM. Нужен ли ИИ обычному человеку?
1.3 API ключ курса или от OpenAI?
1.3.1 Ключ от команды курса
Получаем ключ в боте.
1.3.2 Ключ от OpenAI
Получаем официальный ключ от OpenAI.
1.3.3 Ключ от HuggingFace
Ныряем в Open Source и получаем ключ от HuggingFace.
2.1 Введение в Prompt Engineering
Поясняем за промпты. Техники и лайфхаки для промптинга. Из чего состоит промпт?
2.2 Дизайн промптов в LangChain
Few-shot learning. Output Parser.
2.2.1 Введение в LangChain
Рассказываем про преимущества LangChain.
3.1 Память в LangChain
Переводим LLM в чат-режим. Типы памяти.
3.2 Chains - собери свою цепь
Chains & LCEL.
3.3 Агенты intro
Агенты и цепи. Инструменты (tools).

In [ ]:
r

['Описание курса, начальные требования, для кого этот курс.\n1.1 Как правильно входить в курс\nЦели курса, канал и комьюнити, глоссарий, PET-проект, хард режим vs лайт режим?\n1.2 Общий подход и точки улучшения приложений с LLM\nРассказываем почему важно разбираться в LLM. Нужен ли ИИ обычному человеку?\n1.3 API ключ курса или от OpenAI?\n1.3.1 Ключ от команды курса\nПолучаем ключ в боте.\n1.3.2 Ключ от OpenAI\nПолучаем официальный ключ от OpenAI.\n1.3.3 Ключ от HuggingFace\nНыряем в Open Source и получаем ключ от HuggingFace.',
 '2.1 Введение в Prompt Engineering\nПоясняем за промпты. Техники и лайфхаки для промптинга. Из чего состоит промпт?\n2.2 Дизайн промптов в LangChain\nFew-shot learning. Output Parser.\n2.2.1 Введение в LangChain\nРассказываем про преимущества LangChain.',
 '3.1 Память в LangChain\nПереводим LLM в чат-режим. Типы памяти.\n3.2 Chains - собери свою цепь\nChains & LCEL.\n3.3 Агенты intro\nАгенты и цепи. Инструменты (tools).']

In [ ]:
def get_content_from_sections(text: str) -> List[str]:
    # Регулярное выражение для поиска заголовков основных разделов
    section_pattern = re.compile(r'^\d+\.\s+.*$', re.MULTILINE)
    # Регулярное выражение для поиска заголовков подразделов
    subsection_pattern = re.compile(r'^\d+\.\d+\.\s+.*$', re.MULTILINE)

    # Разделяем текст на основные разделы
    sections = section_pattern.split(text)

    # print(len(sections))
    # print(sections[1].split('\n'))

    number_pattern = re.compile(r'\d')
    temp = ''
    for l in sections:
        for l1 in l.split('\n'):
            if not bool(number_pattern.search(l1)):
                temp += l1
    pattern = re.compile(r'([.?])(?=\S)')
    result = pattern.sub(r'\1 ', temp)
    return(result)

r = get_content_from_sections(text1)
r

'Описание курса, начальные требования, для кого этот курс. Цели курса, канал и комьюнити, глоссарий, PET-проект, хард режим vs лайт режим? Рассказываем почему важно разбираться в LLM. Нужен ли ИИ обычному человеку? Получаем ключ в боте. Получаем официальный ключ от OpenAI. Ныряем в Open Source и получаем ключ от HuggingFace. Поясняем за промпты. Техники и лайфхаки для промптинга. Из чего состоит промпт? Few-shot learning. Output Parser. Рассказываем про преимущества LangChain. Переводим LLM в чат-режим. Типы памяти. Chains & LCEL. Агенты и цепи. Инструменты (tools).'

In [ ]:
import re
from typing import List

def get_content_from_sections(text: str) -> List[str]:
    # Регулярное выражение для поиска заголовков основных разделов
    section_pattern = re.compile(r'^\d+\.\s+.*$', re.MULTILINE)
    # Регулярное выражение для поиска заголовков подразделов
    subsection_pattern = re.compile(r'^\d+\.\d+\.\s+.*$', re.MULTILINE)

    # Разделяем текст на основные разделы
    sections = section_pattern.split(text)

    # print(len(sections))
    # print(sections[1].split('\n'))

    number_pattern = re.compile(r'\d')


    result_t = []
    result = []
    for section in sections:
        if section.strip():

            # Удаляем заголовки подразделов и объединяем текст в одну строку
            section_content = subsection_pattern.sub('', section).strip()
            # print(section_content)
            if section_content:
                result_t.append(section_content)

    for l in result_t:
        temp = ''
        for l1 in l.split('\n'):
            if not bool(number_pattern.search(l1)):
                temp += l1
        # print('---')
        pattern = re.compile(r'([.?])(?=\S)')
        temp = pattern.sub(r'\1 ', temp)
        # print(f"start {temp} stop")
        result.append(temp)



    return result
r = get_content_from_sections(text1)
r

['Описание курса, начальные требования, для кого этот курс. Цели курса, канал и комьюнити, глоссарий, PET-проект, хард режим vs лайт режим? Рассказываем почему важно разбираться в LLM. Нужен ли ИИ обычному человеку? Получаем ключ в боте. Получаем официальный ключ от OpenAI. Ныряем в Open Source и получаем ключ от HuggingFace.',
 'Поясняем за промпты. Техники и лайфхаки для промптинга. Из чего состоит промпт? Few-shot learning. Output Parser. Рассказываем про преимущества LangChain.',
 'Переводим LLM в чат-режим. Типы памяти. Chains & LCEL. Агенты и цепи. Инструменты (tools).']

In [ ]:
len(r)

3

In [ ]:
# r[0].split('\n')

['Описание курса, начальные требования, для кого этот курс.',
 '1.1 Как правильно входить в курс',
 'Цели курса, канал и комьюнити, глоссарий, PET-проект, хард режим vs лайт режим?',
 '1.2 Общий подход и точки улучшения приложений с LLM',
 'Рассказываем почему важно разбираться в LLM. Нужен ли ИИ обычному человеку?',
 '1.3 API ключ курса или от OpenAI?',
 '1.3.1 Ключ от команды курса',
 'Получаем ключ в боте.',
 '1.3.2 Ключ от OpenAI',
 'Получаем официальный ключ от OpenAI.',
 '1.3.3 Ключ от HuggingFace',
 'Ныряем в Open Source и получаем ключ от HuggingFace.']

# Задание 4.11.1 📚 Литературный RAG из pdf 🤖

Загружаем файлы

In [52]:
!wget https://stepik.org/media/attachments/lesson/1084288/The_Daughter_of_The_Commandant.pdf

--2024-08-21 08:58:22--  https://stepik.org/media/attachments/lesson/1084288/The_Daughter_of_The_Commandant.pdf
Resolving stepik.org (stepik.org)... 178.248.239.111
Connecting to stepik.org (stepik.org)|178.248.239.111|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 198595 (194K) [application/pdf]
Saving to: ‘The_Daughter_of_The_Commandant.pdf.1’

The_Daughter_of_The 100%[===================>] 193.94K  1.22MB/s    in 0.2s

2024-08-21 08:58:23 (1.22 MB/s) - ‘The_Daughter_of_The_Commandant.pdf.1’ saved [198595/198595]

In [53]:
import pandas as pd
from tqdm import tqdm

df = pd.read_csv('https://stepik.org/media/attachments/lesson/1084288/pushkin_questions.csv')

Соберем все компоненты для RAG


<center> <img src='https://github.com/a-milenkin/LLM_practical_course/blob/main/images/RAG.png?raw=1' width="800" height="250">

In [54]:
df.head()

                                       question
0               Кого убили раздетой на крыльце?
1           Где Маша остановилась в Петербурге?
2    Почему Гринев и Савельич сбились с дороги?
3   Кто издевался над Машей и морил ее голодом?
4  Куда приговорили отправить Гринева в ссылку?

In [55]:
from langchain.document_loaders import CSVLoader, DataFrameLoader, PyPDFLoader

In [56]:
# Определите Document loader для pdf

file_path = (
    "/content/The_Daughter_of_The_Commandant.pdf"
)
loader = PyPDFLoader(file_path)

documents = loader.load()

Посмотрите, что хранится в переменной documents - может быть сплитер вам не нужен.

In [57]:
documents

[Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 0}, page_content='www.a4format.ru   \nВсе произведения  школьной  программы  в кратком  изложении . — М.: АСТ , 1996.  \n \nИ.О. Родин , Т.М. Пименова  \nКапитанская  дочка  \nКраткое  содержание  \nГлава  1 \nСержант  гвардии  \nГлава  открывается  биографией  Петра  Гринева : отец  служил , вышел  в отставку , \nв семье  было  девять  детей , но все, кроме  Петра , умерли  в младенчестве . Еще до его появ -\nления  на свет Гринева  записали  в Семеновский  полк . До совершеннолетия  он считался  в \nотпуске . Воспитывает  мальчика  дядька  Савельич , под руководством  которого  Петруша  \nосваивает  русскую  грамоту  и учится  судить  о достоинствах  борзого  кобеля . Позже  к нему  \nвыписывают  француза  Бопре , который  должен  был учить  мальчика  «по-французски , по-\nнемецки  и другим  наукам », но воспитанием  Петруши  он не занимался , а пил и гулял  по \nдевичьим . Отец  вскоре  обнаруживает  это и выгоняет  француза . Когда  Петру  пошел  сем-\nнадцатый  год, отец  отправляет  его на службу , но не в Петербург , как надеялся  сын, \nа в Оренбург . Напутствуя  Петра , отец  велит  беречь  ему «платье  снову , а честь  смолоду ». \nПо приезде  в Симбирск  Гринев  знакомится  в трактире  с ротмистром  Зуриным , который  \nучит  его играть  на бильярде , спаивает  и выигрывает  у него  сто рублей . Гринев  «вел себя, \nкак мальчишка , вырвавшийся  на волю ». Наутро  Зурин  требует  выигрыш . Желая  показать  \nхарактер , Гринев  заставляет  Савельича , несмотря  на его протесты , выдать  деньги  и, при-\nстыженный , уезжает  из Симбирска . \nГлава  2 \nВожатый  \nПо дороге  Гринев  просит  у Савельича  прощения  за свое глупое  поведение . В пути  их \nзастает  буран . Они сбиваются  с дороги . Встречают  человека , «сметливость  и тонкость  \nчутья » которого  поражают  Гринева , человек  просит  проводить  их до ближайшего  жилья . \nВ кибитке  Гриневу  снится  сон, будто  он приезжает  в усадьбу , застает  отца  при смерти . \nПетр  подходит  к нему  за благословением  и видит  вместо  отца  мужика  с черной  бородой . \nМать  уверяет  Гринева , что это его посаженый  отец . Мужик  вскакивает , начинает  размахи -\nвать топором , комната  заполняется  мертвыми  телами . Петру  же мужик  улыбается  и зовет  \nпод свое благословение . На постоялом  дворе  Гринев  разглядывает  вожатого . «Он был лет \nсорока , росту  среднего , худощав  и широкоплеч . В черной  бороде  его показывалась  про-\nседь, живые  большие  глаза  так и бегали . Лицо  его имело  выражение  довольно  приятное , \nно плутовское . Волоса  были  обстрижены  в кружок , на нем был оборванный  армяк  и татар -\nские  шаровары ». Вожатый  разговаривает  с хозяином  на «иносказательном  языке »: \n«В огород  летал , конопли  клевал ; швырнула  бабушка  камешком , да мимо ». Гринев  под-\nносит  вожатому  стакан  вина , дарит  ему заячий  тулупчик . Из Оренбурга  старый  товарищ  \nотца  Андрей  Карлович  Р. направляет  Гринева  на службу  в Белогорскую  крепость  \n(40 верст  от города ). \nГлава  3 \nКрепость  \nКрепость  похожа  на деревушку . Распоряжается  всем  разумная  и добрая  жена  комен -\nданта , Василиса  Егоровна . На другое  утро  Гринев  знакомится  с Алексеем  Ивановичем  \nШвабриным , молодым  офицером  «невысокого  роста , с лицом  смуглым  и отменно  не-\nкрасивым , но чрезвычайно  живым ». Швабрин  переведен  в крепость  за дуэль . Швабрин  \nрассказывает  Гриневу  о жизни  в крепости , описывает  семью  коменданта , особенно  '),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 1}, page_content='www.a4format.ru   \n 2\nнелестно  отзывается  о дочери  коменданта  Миронова  Маше . Швабрин  и Гринев  при-\nглашены  на обед  в семью  коменданта . По пути  Гринев  видит  «учения »: комендант  Иван  \nКузьмич  Миронов  командует  взводом  инвалидов . Сам он при этом  одет  «в колпаке  \nи китайчатом  халате ». \nГлава  4 \nПоединок  \nГринев  очень  привязывается  к семейству  коменданта . Его производят  в офицеры . \nГринев  много  общается  со Швабриным , но тот ему нравится  все меньше , а особенно  его \nколкие  замечания  о Маше . Гринев  посвящает  Маше  посредственные  любовные  стихи . \nШвабрин  резко  их критикует , в разговоре  с Гриневым  оскорбляет  Машу . Гринев  называет  \nего лжецом , Швабрин  требует  сатисфакции . Перед  дуэлью  по приказанию  Василисы  \nЕгоровны  их арестовывают , дворовая  девка  Палашка  даже  отнимает  у них шпаги . Через  \nнекоторое  время  Гринев  узнает  от Маши , что Швабрин  за нее сватался , а она отказала  (этим  \nи объясняется  упорное  злословие  Швабрина  в адрес  девушки ). Дуэль  возобновляется , \nГринев  ранен . \nГлава  5 \nЛюбовь  \nМаша  и Савельич  ухаживают  за раненым . Гринев  делает  Маше  предложение . Пишет  \nписьмо  родителям . Швабрин  приходит  навестить  Гринева , признает , что сам был виноват . \nОтец  Гринева  отказывает  сыну  в благословении  (ему известно  и о дуэли , но не от \nСавельича . Гринев  решает , что отцу  сообщил  Швабрин ). Маша  избегает  Гринева , не хочет  \nсвадьбы  без согласия  родителей . Гринев  перестает  бывать  в доме  Мироновых , падает  \nдухом . \nГлава  6 \nПугачевщина  \nКомендант  получает  уведомление  о разбойничьей  шайке  Емельяна  Пугачева , на-\nпадающей  на крепости . Василиса  Егоровна  все выведывает , и слухи  о приступе  распро -\nстраняются  по всей  крепости . Пугачев  призывает  противника  сдаваться . Одно  из воз-\nзваний  попадает  в руки  Миронова  через  пойманного  башкирца , у которого  нет носа , ушей  \nи языка  (последствия  пыток ). Иван  Кузьмич  решает  отослать  Машу  из крепости . Маша  \nпрощается  с Гриневым . Василиса  Егоровна  отказывается  уезжать  и остается  с мужем . \nГлава  7 \nПриступ  \nНочью  казаки  уходят  из Белогорской  крепости  под знамена  Пугачева . Пугачевцы  \nнападают  на крепость . Комендант  и немногочисленные  защитники  крепости  обороняются , \nно силы  неравны . Захватив  крепость , Пугачев  устраивает  «суд». \nИвана  Кузьмича  и его товарищей  казнят  (вешают ). Когда  очередь  доходит  до Гринева , \nСавельич  бросается  в ноги  Пугачеву , умоляя  пощадить  «барского  дитятю », обещает  \nвыкуп . Пугачев  соглашается . Жители  города  и гарнизонные  солдаты  присягают  Пугачеву . \nНа крыльцо  выводят  раздетую  Василису  Егоровну , убивают  ее. Пугачев  уезжает . \nГлава  8 \nНезваный  гость  \nГринева  мучает  мысль  о судьбе  Маши . Ее прячет  у себя попадья , от которой  Гринев  \nузнает , что Швабрин  перешел  на сторону  Пугачева . Савельич  сообщает  Гриневу , что \nузнал  в Пугачеве  вожатого . Пугачев  зовет  Гринева  к себе. Гринев  отправляется . «Все \nобходились  между  собою  как товарищи  и не оказывали  никакого  особенного  предпочте -\nния своему  предводителю ... Каждый  хвастал , предлагал  свои  мнения  и свободно  оспори -'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 2}, page_content='www.a4format.ru   \n 3\nвал Пугачева ». Пугачевцы  поют  песню  про виселицу  («Не шуми , мати  зеленая  дубровуш -\nка»). Гости  Пугачева  расходятся . С глазу  на глаз Гринев  честно  признается , что не считает  \nПугачева  царем . Пугачев : «А разве  нет удачи  удалому ? Разве  в старину  Гришка  Отрепьев  \nне царствовал ? Думай  про меня , что хочешь , а от меня  не отставай ». Пугачев  отпускает  \nГринева  в Оренбург , несмотря  на то, что тот обещает  бороться  против  него . \nГлава  9 \nРазлука  \nПугачев  наказывает  Гриневу  сообщить  оренбургскому  губернатору , что пугачевцы  \nбудут  в городе  через  неделю . Сам Пугачев  выезжает  из Белогорской  крепости , оставляя  \nШвабрина  комендантом . Савельич  подает  Пугачеву  «реестр » разграбленного  барского  \nдобра , Пугачев  в «припадке  великодушия » оставляет  его без внимания  и без наказания . \nЖалует  Гриневу  лошадь  и шубу  со своего  плеча . Маша  заболевает . \nГлава  10 \nОсада  города  \nГринев  едет в Оренбург  к генералу  Андрею  Карловичу . На военном  совете  «не было  \nни одного  военного  человека ». «Все чиновники  говорили  о ненадежности  войск , о невер -\nности  удачи , об осторожности  и тому  подобном . Все полагали , что благоразумнее  оста-\nваться  под прикрытием  пушек  за крепкой  каменной  стеною , нежели  на открытом  поле , \nиспытывать  счастье  оружия ». Чиновники  предлагают  подкупить  людей  Пугачева  \n(назначить  за его голову  большую  цену ). \nУрядник  привозит  из Белогорской  крепости  Гриневу  письмо  от Маши  (Швабрин  \nпринуждает  ее выйти  за него  замуж ). Гринев  просит  генерала  дать ему роту  солдат  и пол-\nсотни  казаков , чтобы  очистить  Белогорскую  крепость . Генерал , разумеется , отказывает . \nГлава  11 \nМятежная  слобода  \nГринев  и Савельич  одни  отправляются  на помощь  Маше . По дороге  их хватают  \nлюди  Пугачева . Пугачев  допрашивает  Гринева  о его намерениях  в присутствии  наперс -\nников . «Один  из них, тщедушный  и сгорбленный  старичок  с седою  бородкою , не имел  \nв себе ничего  замечательного , кроме  голубой  ленты , надетой  через  плечо  по серому  \nармяку . Но ввек не забуду  его товарища . Он был высокого  росту , дороден  и широкоплеч , \nи показался  мне лет сорока  пяти . Густая  рыжая  борода , серые  сверкающие  глаза , нос без \nноздрей  и красноватые  пятна  на лбу и на щеках  придавали  его рябому  широкому  лицу  \nвыражение  неизъяснимое ». Гринев  признается , что едет спасать  сироту  от притязаний  \nШвабрина . Наперсники  предлагают  разобраться  не только  со Швабриным , но и с Грине -\nвым — повесить  обоих . Пугачев  относится  к Гриневу  с явной  симпатией  («долг  платежом  \nкрасен »), обещает  женить  его на Маше . Утром  Гринев  в кибитке  Пугачева  едет в кре-\nпость . В доверительной  беседе  Пугачев  говорит  ему, что хотел  бы пойти  на Москву , но \n«улица  моя тесна ; воли  мне мало . Ребята  мои умничают . Они воры . Мне должно  держать  \nухо востро ; при первой  неудаче  они свою  шею  выкупят  моею  головою ». Пугачев  \nрассказывает  Гриневу  калмыцкую  сказку  об орле  и вороне  (ворон  клевал  падаль , но жил \nдо 300 лет, а орел  был согласен  голодать , «лучше  раз напиться  живой  кровью », но падали  \nне есть, «а там — что Бог даст»). \nГлава  12 \nСирота  \nВ крепости  Пугачев  выясняет , что Швабрин  издевается  над Машей , морит  ее \nголодом . Пугачев  «волею  государя » освобождает  девушку , хочет  тут же обвенчать  ее '),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 3}, page_content='www.a4format.ru   \n 4\nс Гриневым . Швабрин  выдает , что она дочь  капитана  Миронова . Пугачев  решает , что \n«казнить , так казнить , жаловать , так жаловать » и отпускает  Гринева  и Машу . \nГлава  13 \nАрест  \nПо дороге  из крепости  солдаты  арестовывают  Гринева , приняв  его за пугачевца , \nотводят  к своему  начальнику , который  оказываемся  Зуриным . По его совету  Гринев  реша -\nет отправить  Машу  с Савельичем .к своим  родителям , а самому  продолжать  сражаться . \n«Пугачев  был разбит , но не был пойман » и собрал  в Сибири  новые  отряды . Его \nпреследуют , ловят , война  заканчивается . Зурин  получает  приказ  арестовать  Гринева  и от-\nправить  его под караулом  в Казань  в Следственную  комиссию  по делу  Пугачева . \nГлава  14 \nСуд \nПо обвинению  Швабрина  Гринева  подозревают  в том, что он служил  Пугачеву . \nГринева  приговаривают  к ссылке  в Сибирь . Родители  Гринева  очень  привязались  к Маше . \nНе желая  злоупотреблять  их великодушием , Маша  едет в Петербург , останавливается  \nв Царском  Селе , в саду  встречает  императрицу  и просит  о милости  к Гриневу , объясняя , \nчто он попал  к Пугачеву  из-за нее. На аудиенции  императрица  обещает  устроить  судьбу  \nМаши  и простить  Гринева . Гринева  освобождают  из-под стражи . «Он присутствовал  при \nказни  Пугачева , который  узнал  его в толпе  и кивнул  ему головой , которая  через  минуту , \nмертвая  и окровавленная , показана  была  народу ». ')]

In [28]:
# # Определите подходящий Splitter
# from langchain.text_splitter import (
#     CharacterTextSplitter,
#     RecursiveCharacterTextSplitter,
# )

# # splitter = RecursiveCharacterTextSplitter(
# #     chunk_size=500,
# #     chunk_overlap=100,
# #     length_function=len,
# # )

# # splitter = CharacterTextSplitter(
# #     separator="\n\n",  # символ-разделитель, по умолчанию переход к новому абзацу '\n\n'
# #     chunk_size=500,  # размер документа в символах
# #     chunk_overlap=100,  # насколько соседние документы могут перекрывать друг-друга
# #     length_function=len,  # функция, по которой считается размер документа
# #     is_separator_regex=False,  # является ли разделитель регулярным выражением
# # )
# splitter =
# split_documents = splitter.create_documents()
# len(split_documents)

In [58]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
split_documents = splitter.split_documents(documents)
len(split_documents)

16

In [59]:
split_documents

[Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 0}, page_content='www.a4format.ru   \nВсе произведения  школьной  программы  в кратком  изложении . — М.: АСТ , 1996.  \n \nИ.О. Родин , Т.М. Пименова  \nКапитанская  дочка  \nКраткое  содержание  \nГлава  1 \nСержант  гвардии  \nГлава  открывается  биографией  Петра  Гринева : отец  служил , вышел  в отставку , \nв семье  было  девять  детей , но все, кроме  Петра , умерли  в младенчестве . Еще до его появ -\nления  на свет Гринева  записали  в Семеновский  полк . До совершеннолетия  он считался  в \nотпуске . Воспитывает  мальчика  дядька  Савельич , под руководством  которого  Петруша  \nосваивает  русскую  грамоту  и учится  судить  о достоинствах  борзого  кобеля . Позже  к нему  \nвыписывают  француза  Бопре , который  должен  был учить  мальчика  «по-французски , по-\nнемецки  и другим  наукам », но воспитанием  Петруши  он не занимался , а пил и гулял  по \nдевичьим . Отец  вскоре  обнаруживает  это и выгоняет  француза . Когда  Петру  пошел  сем-'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 0}, page_content='немецки  и другим  наукам », но воспитанием  Петруши  он не занимался , а пил и гулял  по \nдевичьим . Отец  вскоре  обнаруживает  это и выгоняет  француза . Когда  Петру  пошел  сем-\nнадцатый  год, отец  отправляет  его на службу , но не в Петербург , как надеялся  сын, \nа в Оренбург . Напутствуя  Петра , отец  велит  беречь  ему «платье  снову , а честь  смолоду ». \nПо приезде  в Симбирск  Гринев  знакомится  в трактире  с ротмистром  Зуриным , который  \nучит  его играть  на бильярде , спаивает  и выигрывает  у него  сто рублей . Гринев  «вел себя, \nкак мальчишка , вырвавшийся  на волю ». Наутро  Зурин  требует  выигрыш . Желая  показать  \nхарактер , Гринев  заставляет  Савельича , несмотря  на его протесты , выдать  деньги  и, при-\nстыженный , уезжает  из Симбирска . \nГлава  2 \nВожатый  \nПо дороге  Гринев  просит  у Савельича  прощения  за свое глупое  поведение . В пути  их \nзастает  буран . Они сбиваются  с дороги . Встречают  человека , «сметливость  и тонкость'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 0}, page_content='Вожатый  \nПо дороге  Гринев  просит  у Савельича  прощения  за свое глупое  поведение . В пути  их \nзастает  буран . Они сбиваются  с дороги . Встречают  человека , «сметливость  и тонкость  \nчутья » которого  поражают  Гринева , человек  просит  проводить  их до ближайшего  жилья . \nВ кибитке  Гриневу  снится  сон, будто  он приезжает  в усадьбу , застает  отца  при смерти . \nПетр  подходит  к нему  за благословением  и видит  вместо  отца  мужика  с черной  бородой . \nМать  уверяет  Гринева , что это его посаженый  отец . Мужик  вскакивает , начинает  размахи -\nвать топором , комната  заполняется  мертвыми  телами . Петру  же мужик  улыбается  и зовет  \nпод свое благословение . На постоялом  дворе  Гринев  разглядывает  вожатого . «Он был лет \nсорока , росту  среднего , худощав  и широкоплеч . В черной  бороде  его показывалась  про-\nседь, живые  большие  глаза  так и бегали . Лицо  его имело  выражение  довольно  приятное ,'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 0}, page_content='сорока , росту  среднего , худощав  и широкоплеч . В черной  бороде  его показывалась  про-\nседь, живые  большие  глаза  так и бегали . Лицо  его имело  выражение  довольно  приятное , \nно плутовское . Волоса  были  обстрижены  в кружок , на нем был оборванный  армяк  и татар -\nские  шаровары ». Вожатый  разговаривает  с хозяином  на «иносказательном  языке »: \n«В огород  летал , конопли  клевал ; швырнула  бабушка  камешком , да мимо ». Гринев  под-\nносит  вожатому  стакан  вина , дарит  ему заячий  тулупчик . Из Оренбурга  старый  товарищ  \nотца  Андрей  Карлович  Р. направляет  Гринева  на службу  в Белогорскую  крепость  \n(40 верст  от города ). \nГлава  3 \nКрепость  \nКрепость  похожа  на деревушку . Распоряжается  всем  разумная  и добрая  жена  комен -\nданта , Василиса  Егоровна . На другое  утро  Гринев  знакомится  с Алексеем  Ивановичем  \nШвабриным , молодым  офицером  «невысокого  роста , с лицом  смуглым  и отменно  не-'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 0}, page_content='данта , Василиса  Егоровна . На другое  утро  Гринев  знакомится  с Алексеем  Ивановичем  \nШвабриным , молодым  офицером  «невысокого  роста , с лицом  смуглым  и отменно  не-\nкрасивым , но чрезвычайно  живым ». Швабрин  переведен  в крепость  за дуэль . Швабрин  \nрассказывает  Гриневу  о жизни  в крепости , описывает  семью  коменданта , особенно'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 1}, page_content='www.a4format.ru   \n 2\nнелестно  отзывается  о дочери  коменданта  Миронова  Маше . Швабрин  и Гринев  при-\nглашены  на обед  в семью  коменданта . По пути  Гринев  видит  «учения »: комендант  Иван  \nКузьмич  Миронов  командует  взводом  инвалидов . Сам он при этом  одет  «в колпаке  \nи китайчатом  халате ». \nГлава  4 \nПоединок  \nГринев  очень  привязывается  к семейству  коменданта . Его производят  в офицеры . \nГринев  много  общается  со Швабриным , но тот ему нравится  все меньше , а особенно  его \nколкие  замечания  о Маше . Гринев  посвящает  Маше  посредственные  любовные  стихи . \nШвабрин  резко  их критикует , в разговоре  с Гриневым  оскорбляет  Машу . Гринев  называет  \nего лжецом , Швабрин  требует  сатисфакции . Перед  дуэлью  по приказанию  Василисы  \nЕгоровны  их арестовывают , дворовая  девка  Палашка  даже  отнимает  у них шпаги . Через  \nнекоторое  время  Гринев  узнает  от Маши , что Швабрин  за нее сватался , а она отказала  (этим'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 1}, page_content='Егоровны  их арестовывают , дворовая  девка  Палашка  даже  отнимает  у них шпаги . Через  \nнекоторое  время  Гринев  узнает  от Маши , что Швабрин  за нее сватался , а она отказала  (этим  \nи объясняется  упорное  злословие  Швабрина  в адрес  девушки ). Дуэль  возобновляется , \nГринев  ранен . \nГлава  5 \nЛюбовь  \nМаша  и Савельич  ухаживают  за раненым . Гринев  делает  Маше  предложение . Пишет  \nписьмо  родителям . Швабрин  приходит  навестить  Гринева , признает , что сам был виноват . \nОтец  Гринева  отказывает  сыну  в благословении  (ему известно  и о дуэли , но не от \nСавельича . Гринев  решает , что отцу  сообщил  Швабрин ). Маша  избегает  Гринева , не хочет  \nсвадьбы  без согласия  родителей . Гринев  перестает  бывать  в доме  Мироновых , падает  \nдухом . \nГлава  6 \nПугачевщина  \nКомендант  получает  уведомление  о разбойничьей  шайке  Емельяна  Пугачева , на-\nпадающей  на крепости . Василиса  Егоровна  все выведывает , и слухи  о приступе  распро -'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 1}, page_content='Глава  6 \nПугачевщина  \nКомендант  получает  уведомление  о разбойничьей  шайке  Емельяна  Пугачева , на-\nпадающей  на крепости . Василиса  Егоровна  все выведывает , и слухи  о приступе  распро -\nстраняются  по всей  крепости . Пугачев  призывает  противника  сдаваться . Одно  из воз-\nзваний  попадает  в руки  Миронова  через  пойманного  башкирца , у которого  нет носа , ушей  \nи языка  (последствия  пыток ). Иван  Кузьмич  решает  отослать  Машу  из крепости . Маша  \nпрощается  с Гриневым . Василиса  Егоровна  отказывается  уезжать  и остается  с мужем . \nГлава  7 \nПриступ  \nНочью  казаки  уходят  из Белогорской  крепости  под знамена  Пугачева . Пугачевцы  \nнападают  на крепость . Комендант  и немногочисленные  защитники  крепости  обороняются , \nно силы  неравны . Захватив  крепость , Пугачев  устраивает  «суд». \nИвана  Кузьмича  и его товарищей  казнят  (вешают ). Когда  очередь  доходит  до Гринева ,'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 1}, page_content='но силы  неравны . Захватив  крепость , Пугачев  устраивает  «суд». \nИвана  Кузьмича  и его товарищей  казнят  (вешают ). Когда  очередь  доходит  до Гринева , \nСавельич  бросается  в ноги  Пугачеву , умоляя  пощадить  «барского  дитятю », обещает  \nвыкуп . Пугачев  соглашается . Жители  города  и гарнизонные  солдаты  присягают  Пугачеву . \nНа крыльцо  выводят  раздетую  Василису  Егоровну , убивают  ее. Пугачев  уезжает . \nГлава  8 \nНезваный  гость  \nГринева  мучает  мысль  о судьбе  Маши . Ее прячет  у себя попадья , от которой  Гринев  \nузнает , что Швабрин  перешел  на сторону  Пугачева . Савельич  сообщает  Гриневу , что \nузнал  в Пугачеве  вожатого . Пугачев  зовет  Гринева  к себе. Гринев  отправляется . «Все \nобходились  между  собою  как товарищи  и не оказывали  никакого  особенного  предпочте -\nния своему  предводителю ... Каждый  хвастал , предлагал  свои  мнения  и свободно  оспори -'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 2}, page_content='www.a4format.ru   \n 3\nвал Пугачева ». Пугачевцы  поют  песню  про виселицу  («Не шуми , мати  зеленая  дубровуш -\nка»). Гости  Пугачева  расходятся . С глазу  на глаз Гринев  честно  признается , что не считает  \nПугачева  царем . Пугачев : «А разве  нет удачи  удалому ? Разве  в старину  Гришка  Отрепьев  \nне царствовал ? Думай  про меня , что хочешь , а от меня  не отставай ». Пугачев  отпускает  \nГринева  в Оренбург , несмотря  на то, что тот обещает  бороться  против  него . \nГлава  9 \nРазлука  \nПугачев  наказывает  Гриневу  сообщить  оренбургскому  губернатору , что пугачевцы  \nбудут  в городе  через  неделю . Сам Пугачев  выезжает  из Белогорской  крепости , оставляя  \nШвабрина  комендантом . Савельич  подает  Пугачеву  «реестр » разграбленного  барского  \nдобра , Пугачев  в «припадке  великодушия » оставляет  его без внимания  и без наказания . \nЖалует  Гриневу  лошадь  и шубу  со своего  плеча . Маша  заболевает . \nГлава  10 \nОсада  города'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 2}, page_content='добра , Пугачев  в «припадке  великодушия » оставляет  его без внимания  и без наказания . \nЖалует  Гриневу  лошадь  и шубу  со своего  плеча . Маша  заболевает . \nГлава  10 \nОсада  города  \nГринев  едет в Оренбург  к генералу  Андрею  Карловичу . На военном  совете  «не было  \nни одного  военного  человека ». «Все чиновники  говорили  о ненадежности  войск , о невер -\nности  удачи , об осторожности  и тому  подобном . Все полагали , что благоразумнее  оста-\nваться  под прикрытием  пушек  за крепкой  каменной  стеною , нежели  на открытом  поле , \nиспытывать  счастье  оружия ». Чиновники  предлагают  подкупить  людей  Пугачева  \n(назначить  за его голову  большую  цену ). \nУрядник  привозит  из Белогорской  крепости  Гриневу  письмо  от Маши  (Швабрин  \nпринуждает  ее выйти  за него  замуж ). Гринев  просит  генерала  дать ему роту  солдат  и пол-\nсотни  казаков , чтобы  очистить  Белогорскую  крепость . Генерал , разумеется , отказывает . \nГлава  11 \nМятежная  слобода'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 2}, page_content='сотни  казаков , чтобы  очистить  Белогорскую  крепость . Генерал , разумеется , отказывает . \nГлава  11 \nМятежная  слобода  \nГринев  и Савельич  одни  отправляются  на помощь  Маше . По дороге  их хватают  \nлюди  Пугачева . Пугачев  допрашивает  Гринева  о его намерениях  в присутствии  наперс -\nников . «Один  из них, тщедушный  и сгорбленный  старичок  с седою  бородкою , не имел  \nв себе ничего  замечательного , кроме  голубой  ленты , надетой  через  плечо  по серому  \nармяку . Но ввек не забуду  его товарища . Он был высокого  росту , дороден  и широкоплеч , \nи показался  мне лет сорока  пяти . Густая  рыжая  борода , серые  сверкающие  глаза , нос без \nноздрей  и красноватые  пятна  на лбу и на щеках  придавали  его рябому  широкому  лицу  \nвыражение  неизъяснимое ». Гринев  признается , что едет спасать  сироту  от притязаний  \nШвабрина . Наперсники  предлагают  разобраться  не только  со Швабриным , но и с Грине -'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 2}, page_content='выражение  неизъяснимое ». Гринев  признается , что едет спасать  сироту  от притязаний  \nШвабрина . Наперсники  предлагают  разобраться  не только  со Швабриным , но и с Грине -\nвым — повесить  обоих . Пугачев  относится  к Гриневу  с явной  симпатией  («долг  платежом  \nкрасен »), обещает  женить  его на Маше . Утром  Гринев  в кибитке  Пугачева  едет в кре-\nпость . В доверительной  беседе  Пугачев  говорит  ему, что хотел  бы пойти  на Москву , но \n«улица  моя тесна ; воли  мне мало . Ребята  мои умничают . Они воры . Мне должно  держать  \nухо востро ; при первой  неудаче  они свою  шею  выкупят  моею  головою ». Пугачев  \nрассказывает  Гриневу  калмыцкую  сказку  об орле  и вороне  (ворон  клевал  падаль , но жил \nдо 300 лет, а орел  был согласен  голодать , «лучше  раз напиться  живой  кровью », но падали  \nне есть, «а там — что Бог даст»). \nГлава  12 \nСирота  \nВ крепости  Пугачев  выясняет , что Швабрин  издевается  над Машей , морит  ее'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 2}, page_content='не есть, «а там — что Бог даст»). \nГлава  12 \nСирота  \nВ крепости  Пугачев  выясняет , что Швабрин  издевается  над Машей , морит  ее \nголодом . Пугачев  «волею  государя » освобождает  девушку , хочет  тут же обвенчать  ее'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 3}, page_content='www.a4format.ru   \n 4\nс Гриневым . Швабрин  выдает , что она дочь  капитана  Миронова . Пугачев  решает , что \n«казнить , так казнить , жаловать , так жаловать » и отпускает  Гринева  и Машу . \nГлава  13 \nАрест  \nПо дороге  из крепости  солдаты  арестовывают  Гринева , приняв  его за пугачевца , \nотводят  к своему  начальнику , который  оказываемся  Зуриным . По его совету  Гринев  реша -\nет отправить  Машу  с Савельичем .к своим  родителям , а самому  продолжать  сражаться . \n«Пугачев  был разбит , но не был пойман » и собрал  в Сибири  новые  отряды . Его \nпреследуют , ловят , война  заканчивается . Зурин  получает  приказ  арестовать  Гринева  и от-\nправить  его под караулом  в Казань  в Следственную  комиссию  по делу  Пугачева . \nГлава  14 \nСуд \nПо обвинению  Швабрина  Гринева  подозревают  в том, что он служил  Пугачеву . \nГринева  приговаривают  к ссылке  в Сибирь . Родители  Гринева  очень  привязались  к Маше .'),
 Document(metadata={'source': '/content/The_Daughter_of_The_Commandant.pdf', 'page': 3}, page_content='Глава  14 \nСуд \nПо обвинению  Швабрина  Гринева  подозревают  в том, что он служил  Пугачеву . \nГринева  приговаривают  к ссылке  в Сибирь . Родители  Гринева  очень  привязались  к Маше . \nНе желая  злоупотреблять  их великодушием , Маша  едет в Петербург , останавливается  \nв Царском  Селе , в саду  встречает  императрицу  и просит  о милости  к Гриневу , объясняя , \nчто он попал  к Пугачеву  из-за нее. На аудиенции  императрица  обещает  устроить  судьбу  \nМаши  и простить  Гринева . Гринева  освобождают  из-под стражи . «Он присутствовал  при \nказни  Пугачева , который  узнал  его в толпе  и кивнул  ему головой , которая  через  минуту , \nмертвая  и окровавленная , показана  была  народу ».')]

# Выбираем Embedding models

## 🔱 Эмбеддинги от OpenAI (API)

In [ ]:
# # Если используете ключ от OpenAI запустите эту ячейку
# from langchain_openai import OpenAIEmbeddings

# embeddings_api_model = OpenAIEmbeddings()

In [ ]:
# Если используете ключ курса, запустите эту ячейку
from utils import OpenAIEmbeddings

embeddings_api_model = OpenAIEmbeddings(course_api_key=course_api_key)

## 🔱 Эмбеддинги от HuggingFace 🤗
Переключитесь на среду с GPU, если хотите использовать видеокарту.

In [32]:
from langchain.embeddings import HuggingFaceEmbeddings

# Если у вас нет видеокарты, укажите 'device': 'cpu'
hf_embeddings_model = HuggingFaceEmbeddings(
    model_name="cointegrated/LaBSE-en-ru", model_kwargs={"device": "cpu"}
)

# Выбираем 🗂 Vector Store

In [33]:
from langchain.vectorstores import FAISS

db = FAISS.from_documents(split_documents, hf_embeddings_model)

# Определим 🎣 Retriever

In [34]:
retriever = db.as_retriever()

# 🚰 RAG Pipeline - подключаем RAG к LLM

In [60]:
from langchain.schema import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough

# Создаём простой шаблон
template = """
Answer the question based only on the following context:

{context}

Question: {question}
"""
# Создаём промпт из шаблона
prompt = ChatPromptTemplate.from_template(template)


# Объявляем функцию, которая будет собирать строку из полученных документов
def format_docs(docs):
    return "\n\n".join([d.page_content for d in docs])


# Создаём цепочку
# chain = (
#     {"context": retriever | format_docs, "question": RunnablePassthrough()}
#     | prompt
#     | hf_embeddings_model
#     | StrOutputParser()
# )

# Создаём цепочку
chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

In [40]:
# split_documents

In [43]:
# from langchain.text_splitter import RecursiveCharacterTextSplitter

# splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
# split_documents = splitter.split_documents(documents)
# len(split_documents)

16

In [44]:
# from langchain.embeddings import HuggingFaceEmbeddings

# # Если у вас нет видеокарты, укажите 'device': 'cpu'
# hf_embeddings_model = HuggingFaceEmbeddings(
#     model_name="cointegrated/LaBSE-en-ru", model_kwargs={"device": "cpu"}
# )

In [45]:
# from langchain.vectorstores import FAISS

# db = FAISS.from_documents(split_documents, hf_embeddings_model)

In [46]:
# retriever = db.as_retriever()

In [50]:
# from langchain.schema import StrOutputParser
# from langchain_core.prompts import ChatPromptTemplate
# from langchain_core.runnables import RunnablePassthrough

# # Создаём простой шаблон
# template = """
# Answer the question based only on the following context:

# {context}

# Question: {question}
# """
# # Создаём промпт из шаблона
# prompt = ChatPromptTemplate.from_template(template)

# # Объявляем функцию, которая будет собирать строку из полученных документов
# def format_docs(docs):
#     return "\n\n".join([d.page_content for d in docs])

# # Создаём цепочку
# chain = (
#     {"context": retriever | format_docs, "question": RunnablePassthrough()}
#     | prompt
#     | StrOutputParser()
# )

In [62]:
answers = [] # Список, где будем хранить ответы модели

for text_input in tqdm(df['question']):
    answer = chain.invoke(text_input)
    answers.append(answer) # Добавляем ответ в список
    # break # Для отладки. Уберите, когда убедитесь, что на одном примере работает

df['answer'] = answers # Создаём новый столбец из ответов модели
df.to_csv('4_1_11_solution.csv', index=False) # Сохраняем файл, отправляем на Stepik, получаем баллы :)

100%|██████████| 15/15 [00:18<00:00,  1.21s/it]

In [63]:
df

,question,answer
0,Кого убили раздетой на крыльце?,Убили раздетую Василису Егоровну.
1,Где Маша остановилась в Петербурге?,Маша остановилась в Царском Селе.
2,Почему Гринев и Савельич сбились с дороги?,Гринев и Савельич сбились с дороги из-за буран...
3,Кто издевался над Машей и морил ее голодом?,Швабрин издевался над Машей и морил ее голодом.
4,Куда приговорили отправить Гринева в ссылку?,Гринева приговорили отправить в ссылку в Сибирь.
5,Сколько детей было в семье Петра Гринева?,"В семье Петра Гринева было девять детей, но вс..."
6,Кто воспитывал Петра Гринева?,Дядька Савельич.
7,"Сколько казаков попросил Гринев, чтобы очистит...","Гринев попросил у генерала полсотни казаков, ч..."
8,Как далеко находилась от города Белогорская кр...,От города Белогорская крепость находилась на р...
9,Как звали дочку коменданта?,Маша
10,Что Петя подарил вожатому?,Петя подарил вожатому лошадь и шубу.
11,Какое напутствие дал Петру отец?,"Отцу велел беречь Петру ""платье снову, а честь..."
12,Кого Пугачев оставил комендантом Белогорской к...,Пугачев оставил Швабрина комендантом Белогорск...
13,Почему Швабрина перевели в крепость?,Швабрина перевели в крепость за дуэль.
14,Кого просил пощадить Савельич у Пугачева?,"Савельич просил пощадить ""барского дитятю"", то..."

In [42]:
answers = [] # Список, где будем хранить ответы модели

for text_input in tqdm(df['question']):
    answer = chain.invoke(text_input)
    answers.append(answer) # Добавляем ответ в список
    break # Для отладки. Уберите, когда убедитесь, что на одном примере работает

  0%|          | 0/15 [00:00<?, ?it/s]

ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)

In [65]:
answers

['Убили раздетую Василису Егоровну.',
 'Маша остановилась в Царском Селе.',
 'Гринев и Савельич сбились с дороги из-за бурана, который они встретили по пути.',
 'Швабрин издевался над Машей и морил ее голодом.',
 'Гринева приговорили отправить в ссылку в Сибирь.',
 'В семье Петра Гринева было девять детей, но все, кроме Петра, умерли в младенчестве.',
 'Дядька Савельич.',
 'Гринев попросил у генерала полсотни казаков, чтобы очистить Белогорскую крепость.',
 'От города Белогорская крепость находилась на расстоянии 40 верст.',
 'Маша',
 'Петя подарил вожатому лошадь и шубу.',
 'Отцу велел беречь Петру "платье снову, а честь смолоду".',
 'Пугачев оставил Швабрина комендантом Белогорской крепости.',
 'Швабрина перевели в крепость за дуэль.',
 'Савельич просил пощадить "барского дитятю", то есть Гринева.']

In [ ]:
df['answer'] = answers # Создаём новый столбец из ответов модели

In [ ]:
df.to_csv('4_1_11_solution.csv', index=False) # Сохраняем файл, отправляем на Stepik, получаем баллы :)

# Решения других

In [ ]:
from dotenv import load_dotenv
import os
from langchain_openai import ChatOpenAI
import pandas as pd
from tqdm import tqdm

load_dotenv(dotenv_path='.env.txt') # load env variables
api_key = os.getenv("OPENAI_API_KEY") # load api key

os.environ['OPENAI_API_KEY'] = api_key # set api key
llm = ChatOpenAI(temperature=0.0) # set llm

df = pd.read_csv('pushkin_questions.csv') # read csv file from folder with project


from langchain_community.document_loaders import PyPDFLoader
file_path = "The_Daughter_of_The_Commandant.pdf"
loader = PyPDFLoader(file_path)
pages = loader.load_and_split()

# Объединение всех страниц в один текст
full_text = "\n\n".join([page.page_content for page in pages])


from langchain.text_splitter import RecursiveCharacterTextSplitter
import re

# можно по другому ещще разбить сплитеры
# Кастомный сплиттер для разделения по главам
class ChapterTextSplitter(RecursiveCharacterTextSplitter):
    def __init__(self, chunk_size=1000, chunk_overlap=100, separators=None):
        super().__init__(chunk_size=chunk_size, chunk_overlap=chunk_overlap, separators=separators)

    def split_text(self, text):
        # Разделение текста по главам с использованием регулярного выражения
        chapters = re.split(r'(Глава\s+\d+)', text)
        chunks = []
        for i in range(1, len(chapters), 2):
            chapter_title = chapters[i]
            chapter_text = chapters[i + 1]
            chunks.append(chapter_title + chapter_text)
        return chunks

# Объединение всех страниц в один текст
full_text = "\n\n".join([page.page_content for page in pages])

# Инициализация и использование кастомного сплиттера
splitter = ChapterTextSplitter(chunk_size=1000, chunk_overlap=100)
chapters = splitter.split_text(full_text)
len(chapters)


from langchain_openai import OpenAIEmbeddings
from langchain.docstore.document import Document
from langchain.vectorstores import FAISS

# Преобразуем главы в список объектов Document... нужно преобразовать в формат которыый принимает метод from_documents
documents = [Document(page_content=chapter) for chapter in chapters]

embeddings_api_model = OpenAIEmbeddings()

db = FAISS.from_documents(documents, embeddings_api_model)
db.save_local("Pushkin_local")


# Задаём ретривер
retriever = db.as_retriever(search_type='similarity',
                           k=3,
                           score_threshold=None)


from langchain.schema import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough

# Создаём простой шаблон!!! ВАЖНО. промпт можно улучшить. даже нужно. чтобы он более конкретные ответы давал
template = """
Ответь четко, просто и без лишних слов и символовна поставленный вопрос согласно контексту:

{context}

Question: {question}
"""
# Создаём промпт из шаблона
prompt = ChatPromptTemplate.from_template(template)

# Объявляем функцию, которая будет собирать строку из полученных документов
def format_docs(docs):
    #print(type(docs[0].page_content))
    return "\n\n".join(docs[0].page_content for d in docs)


# str_to_llm = format_docs(retriever.invoke("Кого убили раздетой на крыльце?"))

# Создаём цепочку
chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

#chain.invoke("Кого убили раздетой на крыльце?")


answers = [] # Список, где будем хранить ответы модели

for text_input in tqdm(df['question']):
    answer = chain.invoke(text_input)
    answers.append(answer) # Добавляем ответ в список



df['answer'] = answers


df.to_csv('4_1_11_solution.csv', index=False)

In [ ]:
В общем то всё по файлу из курса.
Лишь не получилось использовать embeddings от HuggingFaceEmbeddings, хотя перевести в вектора тексты удалось, поэтому использовал курса embeddings = OpenAIEmbeddings(course_api_key=course_api_key)
import pandas as pd
from tqdm import tqdm
from langchain.schema import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_community.document_loaders import DirectoryLoader, UnstructuredPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import FAISS

from utils import OpenAIEmbeddings, ChatOpenAI

llm = ChatOpenAI(temperature=0.0, course_api_key=course_api_key)

df = pd.read_csv('pushkin_questions.csv')
loader = DirectoryLoader(
    'pdf',
    glob="**/*.pdf",
    loader_cls=UnstructuredPDFLoader
)

documents = loader.load()
splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100,
    length_function=len,
)

texts = [doc.page_content for doc in documents]

split_documents = splitter.create_documents(texts)
embeddings = OpenAIEmbeddings(course_api_key=course_api_key)
db = FAISS.from_documents(
    split_documents, embeddings
)
db.save_local("puskin_db")
retriever = db.as_retriever(
    search_type="similarity",
    k=4,
    score_threshold=None,
)


template = """
Ответь на вопросы основываясь только на следующем контексте:

{context}

Если ты не уверен в ответе исходя из контекста, то напиши "не знаю".
Длина каждого ответа не должна превышать 70 символов. Нужны четкие, краткие и прямые ответы.

Question: {question}
"""

prompt = ChatPromptTemplate.from_template(template)

def format_docs(docs):
    return "\n\n".join([d.page_content for d in docs])

chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)
answers = []

for text_input in tqdm(df['question']):
    answer = chain.invoke(text_input)
    answers.append(answer)
    # break
df['answer'] = answers
df.to_csv('4_1_11_solution.csv', index=False)

In [ ]:
template = """\
Ответь на вопрос кратким ответом, руководствуясь контекстом ниже.
Если не уверен в ответе исходя из контекста, то напиши "не знаю".

Контекст:
{context}

Вопрос:
{question}

Ответ:
"""

In [ ]:
Но тут скорее упор делался на на промпт, а на другие вещи.
Например, на очистке текста: отформатировал переносы, удалил ненужные ссылки и т.д.
Разбиение на чанки отдал на откуп токенайзеру "bert-base-uncased"

tokenizer = Tokenizer.from_pretrained("bert-base-uncased")
splitter = HuggingFaceTextSplitter(tokenizer, trim_chunks=True)
chunks = splitter.chunks(text, chunk_capacity=(100,500))
Из rag db доставал по 10 чанков, да и вообще поигрался с параметрами:

retriever = db.as_retriever(
    search_kwargs={'k': 10}
    # search_type="similarity_score_threshold",
    # search_kwargs={"k": 20, "score_threshold": 0.1,},
)
Использовал локальную модель saiga_mistral_7B с температурой 0.1. При разной генерации ответа на последний вопрос выдаёт ответ: "Гринева", "Савельича" и весьма!!! редкий вариант "барского дитятю". Получается последний вопрос с помощью LLM так и не победил стабильностью, только перегенерацией (хотя "Гринева" вроде тоже правильный ответ, но не засчитывается).

Дополнительно пробовал требовать более развёрнутые ответы для контроля LLM в промпте. И конечно тестить разные локальные модели: "miqu_70B", "mistral_instruct_v0.1_v0.2", etc. для поиска более подходящей по задаче.

Поэтому тут работа скорее не с промптом (только более сложные ответы для контроля), а сколько со всем пайплайном в совокупности.