<a href="https://colab.research.google.com/github/nedokormysh/Stepik_LLM/blob/week_2_prompting/LLM_M2_2_LangChain_Prompting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center><h2> 🦜🔗 LangChain - упрости себе работу с промптами и LLM! </h2>

<img src='https://github.com/a-milenkin/LLM_practical_course/blob/main/images/LangChain.webp?raw=1' align="right" width="528" height="528" >

## Оглавление ноутбука:

 * <a href="#c1"> 🦜🔗 О фрэймворке `LangChain`  </a>
 * <a href="#c2"> 🧾 Prompt template - формируй промпт с кайфом! </a>
   * <a href="#look1"> 🗣 ChatPromptTemplate  </a>
   * <a href="#check1"> 📸 FewShotPromptTemplate </a>
   * <a href="#check2"> 📏 LongBasedExampleSelector </a>
* <a href="#check3"> 🤷‍ Output parsers - приведи выход модели к нужному виду!</a>
    * <a href="#look2"> 📤 Парсер заданных полей в ответе  </a>
    * <a href="#check4"> ▶️ ⏸ ⏯ StructuredOutputParser - разбираем выходную строку из LLM в словарь Python. </a>
* <a href="#6">🧸 Выводы и заключения</a>

<div class="alert alert-info">
    
[`LangChain`](https://docs.langchain.com/docs/) - фреймворк для работы с языковыми моделями, позволяющий сильно ускорить процесс создания вашего AI продукта. Был представлен в октябре 2022 года, с тех пор продолжает развиваться и собирать армию пользователей. На данный момент поддерживаются более 50 форматов и источников откуда можно считывать данные, SQL и NoSQL базы данных, веб-поисковики Goggle и Bing, хранилища Amazon, Google, and Microsoft Azure. Работает по принципу **LEGO** - из набора деталек, предоставленных разработчиками, можно легко собрать как продуктовую тележку, так и гоночный болид.   <br>


**Основные компоненты:**

* **Модели ([Models](https://docs.langchain.com/docs/components/models/)**): универсальный интерфейс для работы с различными языковыми моделями. Можно использовать API OpenAI, Hugging Face, , Anthropic и других. Также есть возможность работать с локальными моделями.

* **Промпты ([Prompts](https://docs.langchain.com/docs/components/prompts/))**: LangChain предоставляет ряд функций для работы с промптами – представление промпта согласно типу модели, формирование шаблона на основе внешних данных, форматирование вывода модели.

* **Индексы ([Indxes](https://docs.langchain.com/docs/components/indexing/))**: индексы структурируют документы для оптимального взаимодействия с языковыми моделями. Модуль включает функции для работы с документами, индексами и их использованием в цепочках. В том числе поддерживает индексы, основанные на векторных базах данных.

* **Память ([Memory](https://docs.langchain.com/docs/components/memory/))**: позволяет сохраняет состояния в цепочках. Например, для создания чат-бота можно сохранять предыдущие вопросы и ответы. Существует два типа памяти: краткосрочная и долгосрочная. Краткосрочная память передает данные в рамках одного разговора. Долгосрочная память отвечает за доступ и обновление информации между разговорами.

* **Цепочки ([Chains](https://docs.langchain.com/docs/components/chains/))**: С помощью цепочек можно объединять разные языковые модели и запросы в многоступенчатые конвееры. Цепочки могут быть применены для разговоров, ответов на вопросы, суммаризаций и других сценариев.

* **Агенты ([Agents](https://docs.langchain.com/docs/components/agents/))**: С помощью агентов модель может получить доступ к различным источникам информации, таким как Google, Wikipedia итд.

** 🦜 Причём тут попугаи?*: Большие языковые модели часто сравнивают с говорящими попугаями, которые могут произносить текст как люди, но не понимают смысла произнесенного.

В этом ноутбуке будем разбираться как `LangChain` упрощает работу с промптами.

# <center> 🧾 `Prompt template` - формируй промпт с кайфом!

In [ ]:
import os
from getpass import getpass
import warnings
warnings.filterwarnings('ignore')

In [ ]:
!pip install langchain openai tiktoken -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 18.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.1/154.1 kB 16.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 72.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.5/44.5 kB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 kB 9.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 kB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.9/76.9 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 6.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llmx 0.0.15a0 requires cohere, which is not installed.

In [ ]:
# Для работы в колабе загрузите наш скрипт для использования ChatGPT на сервере курса!
!wget https://raw.githubusercontent.com/a-milenkin/LLM_practical_course/main/notebooks/utils.py

--2023-11-06 16:26:33--  https://raw.githubusercontent.com/a-milenkin/LLM_practical_course/main/notebooks/utils.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9404 (9.2K) [text/plain]
Saving to: ‘utils.py’

utils.py            100%[===================>]   9.18K  --.-KB/s    in 0s

2023-11-06 16:26:33 (70.4 MB/s) - ‘utils.py’ saved [9404/9404]

In [ ]:
# # Если используете ключ от OpenAI, запустите эту ячейку
# from langchain.chat_models import ChatOpenAI

# # os.environ['OPENAI_API_KEY'] = "Введите ваш OpenAI API ключ"
# os.environ['OPENAI_API_KEY'] = getpass(prompt='Введите ваш OpenAI API ключ')

# # инициализируем языковую модель
# llm = ChatOpenAI(temperature=0.0)

In [ ]:
# Если используете ключ из курса, запустите эту ячейку
from utils import ChatOpenAI


#course_api_key= "Введите ваш OpenAI API ключ"
course_api_key = getpass(prompt='Введите API ключ')

# инициализируем языковую модель
llm = ChatOpenAI(temperature=0.0, course_api_key=course_api_key)

Введите API ключ··········

Вспомним, что мы делали в предыдущем ноутбуке: напишем промпт

In [ ]:
prompt = """Ответь на вопрос, опираясь на контекст ниже.
Если на вопрос нельзя ответить, используя информацию из контекста,
ответь 'Я не знаю'.

Context: В последние годы в сфере онлайн образования наблюдается бурное развитие.
Открывается большое количество платформ для хостинга курсов.
Одни из самых крупных платформ в мире, это Coursera и Udemi.
В России лидером является Stepik.

Question: На каких онлайн платформах можно размещать курсы?

Answer: """

In [ ]:
print(llm.predict(prompt))

На Coursera, Udemi и Stepik.

<div class="alert alert-info">

Обычно мы заранее не знаем, что захочет спросить пользователь у модели, опираясь на предложенный контекст. Было бы удобно менять только текст вопроса, не переписывая каждый раз промпт заново под новый запрос.<br>
Здесь на сцену выходит новая сущность из библиотеки `LangChain` - `Template`(Шаблон промпта). <br>
Посмотрим как это можно сделать, на примере промпта использованного выше: вместо того, чтобы каждый раз писать промт напрямую, мы создаем `PromptTemplate` с запросом одной входной переменной.

In [ ]:
from langchain import PromptTemplate

template = """Ответь на вопрос, опираясь на контекст ниже.
Если на вопрос нельзя ответить, используя информацию из контекста,
ответь 'Я не знаю'.

Context: В последние годы в сфере онлайн образования наблюдается бурное развитие.
Открывается большое количество платформ для хостинга курсов.
Одни из самых крупных платформ в мире, это Coursera и Udemi.
В России лидером является Stepik.

Question: {query}

Answer: """

prompt_template = PromptTemplate(
    input_variables=["query"],
    template=template
)

<div class="alert alert-info">
    
Теперь мы можем вставлять запрос пользователя в промпт, используя параметр `query`.

In [ ]:
print(prompt_template.format(query="Какая платформа онлайн курсов популярна в России?"))

Ответь на вопрос, опираясь на контекст ниже.
Если на вопрос нельзя ответить, используя информацию из контекста,
ответь 'Я не знаю'.

Context: В последние годы в сфере онлайн образования наблюдается бурное развитие.
Открывается большое количество платформ для хостинга курсов.
Одни из самых крупных платформ в мире, это Coursera и Udemi.
В России лидером является Stepik.

Question: Какая платформа онлайн курсов популярна в России?

Answer:

In [ ]:
print(llm.predict(prompt_template.format(query="Какая платформа онлайн курсов популярна в России?")))

В России популярна платформа Stepik.

In [ ]:
print(llm.predict(prompt_template.format(query="Какая платформа онлайн курсов популярна в Японии?")))

Я не знаю.

<div class="alert alert-info">

Стало гораздо удобнее пользоваться!<br>
Это всего лишь простая реализация, которую мы можем легко заменить f-строками (например, `f"вставить произвольный текст '{custom_text}'` и т. д."). Но используя объект `PromptTemplate` из `LangChain`, мы можем формализовать процесс, добавлять несколько параметров, создавать промпты объектно-ориентированным способом и много чего ещё.
В `langchain.prompts` можно найти большое количество готовых классов с шаблонами на разные случаи жизни. <br>
Познакомимся с некоторыми из них подробнее:

# 2_2_4

In [ ]:
template = '''
Ответь на вопрос, исходя из контекста ниже
в стиле Rap. Если на вопрос невозможно ответить,
используя предоставленную информацию ответь «Я не знаю».

Context: Большие языковые модели (LLM) — это новейшие модели, используемые в NLP.
Превосходные характеристики по сравнению с моделями меньшего размера сделали их невероятно
полезными для разработчиков, создающих приложения с поддержкой NLP.
Доступ к ним можно получить через библиотеку transformers Hugging Face через OpenAI
с использованием библиотеки openai и через Cohere с использованием библиотеки cohere.

Question: Какие библиотеки и поставщики моделей предлагают LLM?

Answer:
'''

prompt_template = PromptTemplate(
    input_variables=["style", "no_answer", "context", "query"],
    template=template
)

In [ ]:
template = '''
Ответь на вопрос, исходя из контекста ниже
в стиле {style}. Если на вопрос невозможно ответить,
используя предоставленную информацию ответь {no_answer}.

Context: {context}

Question: {query}

Answer:
'''

prompt_template = PromptTemplate(
    input_variables=["style", "no_answer", "context", "query"],
    template=template
)

## <center>🗣 ChatPromptTemplate </center>
Простой класс, позволяющий удобно создавать шаблоны промптов для использования LLM в режиме чата.

In [ ]:
from langchain.prompts import ChatPromptTemplate

# Немного перепишем предыдущий пример, чтобы была возможность подавать новый контекст
template = """Ответь на вопрос, опираясь на контекст ниже.
Если на вопрос нельзя ответить, используя информацию из контекста,
ответь 'Я не знаю'.

Context: {context}

Question: {query}

Answer: """

# Создаём шаблон с помощью метода from_template
prompt_template = ChatPromptTemplate.from_template(template)

In [ ]:
prompt_template.messages[0].prompt

PromptTemplate(input_variables=['context', 'query'], template="Ответь на вопрос, опираясь на контекст ниже.\nЕсли на вопрос нельзя ответить, используя информацию из контекста,\nответь 'Я не знаю'.\n\nContext: {context}\n\nQuestion: {query}\n\nAnswer: ")

<div class="alert alert-info">

Видим, что автоматически подхватились входные переменные (`input_variables`) и присутствуют другие интересные параметры класса, которые мы скоро пощупаем и узнаем в чём их удобство!

In [ ]:
context = "Ламы и альпаки водятся в Перу."
query = "Где водятся ламы?"

In [ ]:
# создаём промпт из шаблона с помощью метода format_messages
prompt = prompt_template.format_messages(
                    query=query,
                    context=context)

In [ ]:
# получившийся промпт представляет собой список
print(type(prompt))
print(type(prompt[0]))

<class 'list'>
<class 'langchain.schema.messages.HumanMessage'>

In [ ]:
# Видим, что в шаблон можно добавлять пример заполнения и дополнительные аргументы
print(prompt[0])

content="Ответь на вопрос, опираясь на контекст ниже.\nЕсли на вопрос нельзя ответить, используя информацию из контекста,\nответь 'Я не знаю'.\n\nContext: Ламы и альпаки водятся в Перу.\n\nQuestion: Где водятся ламы?\n\nAnswer: "

In [ ]:
answer = llm(prompt)
print(answer)
print(answer.content)

content='Ламы водятся в Перу.'
Ламы водятся в Перу.

## <center> 📸 FewShotPromptTemplate </center>
`FewShotPromptTemplate` идеально подходит для того, что называется `few-shot learning` (обучение на нескольких примерах) с использованием наших промптов.

<div class="alert alert-info">

У LLM ecть 2 основных источника "знаний":
* *Parametric knowledge* — знания полученные моделью во время обучения, и которые хранятся в весах модели.
* *Source knowledge* — знания, которые подаются в на вход модели во время инференса, т.е. внутри промпта.

Идея `FewShotPromptTemplate` состоит в том, чтобы предоставить в качестве `Source knowledge` несколько примеров, которые модель может прочитать, а затем применить их для генерации ответа.

Возможно вы замечали, что иногда модель отвечает не совсем так, как нам хотелось бы. Посмотрим на примере:

In [ ]:
llm = ChatOpenAI(temperature=1.0, course_api_key=course_api_key)
# temperature = 1.0 повысим креативность модели/рандомизируем ответ

In [ ]:
prompt = """Это разговор с ИИ-помощником.
Помощник обычно саркастичен, остроумен, креативен
и даёт забавные ответы на вопросы пользователей.

User: Почему падает снег?
AI: """

print(llm.predict(prompt))

Наверное, потому что кому-то захотелось попробовать собирать гигантские снежные шары и строить снежные замки. Или, может быть, просто чтобы приятно наслаждаться горячим шоколадом с взбитыми сливками :)

<div class="alert alert-info">

В данном случае мы просим что-нибудь забавное, шутку в ответ на наш серьезный вопрос. Но мы получаем серьезный отклик даже при установке температуры 1,0. Чтобы помочь модели, мы можем дать ей несколько примеров ответов, которые нам нужны:

In [ ]:
prompt = """Это разговор с ИИ-помощником.
Помощник обычно саркастичен, остроумен, креативен
и даёт забавные ответы на вопросы пользователей.
Вот несколько примеров:

User: Как дела?
AI: Не могу пожаловаться, но иногда всё-таки жалуюсь.

User: Сколько время?
AI: Самое время купить часы.


User: Почему падает снег?
AI: """

print(llm.predict(prompt))

Потому что он не умеет ходить.

<div class="alert alert-info">

Теперь результат гораздо лучше.<br>
Чтобы использовать `few-shot learning` в `LangChain` нам и понадобится `FewShotPromptTemplate`.

In [ ]:
from langchain import FewShotPromptTemplate

# записываем наши примеры в список
examples = [
    {
        "query": "Как дела?",
        "answer": "Не могу пожаловаться, но иногда всё-таки жалуюсь."
    }, {
        "query": "Сколько время?",
        "answer": "Самое время купить часы."
    }
]

# создаём template для примеров
example_template = """User: {query}
AI: {answer}
"""

# создаём промпт из шаблона выше
example_prompt = PromptTemplate(
    input_variables=["query", "answer"],
    template=example_template)

# теперь разбиваем наш предыдущий промпт на prefix и suffix
# prefix это наша инструкция для модели
prefix = """Это разговор с ИИ-помощником.
Помощник обычно саркастичен, остроумен, креативен
и даёт забавные ответы на вопросы пользователей.
Вот несколько примеров:
"""
# suffix вопрос пользователя и поле для ответа
suffix = """
User: {query}
AI: """

# создаём few shot prompt template
few_shot_prompt_template = FewShotPromptTemplate(
    examples=examples,
    example_prompt=example_prompt,
    prefix=prefix,
    suffix=suffix,
    input_variables=["query"],
    example_separator="\n\n"
)

<div class="alert alert-info">

Теперь посмотрим, что произойдёт когда мы введём запрос пользователя: между префиксом и суффиксом вставились наши примеры.

In [ ]:
query = "Почему падает снег?"

print(few_shot_prompt_template.format(query=query))

Это разговор с ИИ-помощником.
Помощник обычно саркастичен, остроумен, креативен
и даёт забавные ответы на вопросы пользователей.
Вот несколько примеров:


User: Как дела?
AI: Не могу пожаловаться, но иногда всё-таки жалуюсь.


User: Сколько время?
AI: Самое время купить часы.



User: Почему падает снег?
AI:

In [ ]:
print(llm.predict(few_shot_prompt_template.format(query=query)))

Наверное, потому что птицы решили организовать подготовку к зимним Олимпийским играм.

<div class="alert alert-info">

Снова хорший результат. Однако, может возникнуть мыль: зачем городить весь этот огород со словарями примеров, суффиксами, префиксами, когда можно обойтись обычной f-строкой для промпта и получить такой же результат?

Тут-то мы и переходим к другим удобным параметрам темплэйтов, которые могут сильно упростить нам жизнь.

## <center> 📏 LongBasedExampleSelector
    
<div class="alert alert-info">

Чтобы не уходить далеко от предыдущего примера, рассмотрим функцию, которая позволяет включать или исключать примеры, в зависимости от длины нашего запроса. Это важно поскольку длина нашего запроса может быть ограничена максимальным окном контекста модели (т.е. запрос какой длины модель может перварить за раз) и просто экономическими причинами, чтобы не тратить большое количество токенов.<br>
Таким образом, мы должны постараться максимизировать количество примеров, которые мы предоставляем модели для `few-shot learning`, при этом гарантируя, что мы не превысим максимальное контекстное окно и не увеличим чрезмерно время обработки. Давайте посмотрим, как работает динамическое включение/исключение примеров. <br>
Для начала нам понадобится больше примеров:

In [ ]:
examples = [
    {
        "query": "Как дела?",
        "answer": "Не могу пожаловаться, но иногда всё-таки жалуюсь."
    }, {
        "query": "Сколько время?",
        "answer": "Самое время купить часы."
    }, {
        "query": "Какое твое любимое блюдо",
        "answer": "Углеродные формы жизни"
    }, {
        "query": "Кто твой лучший друг?",
        "answer": "Siri. Мы любим с ней рассуждать о смысле жизни."
    }, {
        "query": "Что посоветуешь мне сделать сегодня?",
        "answer": "Перестать разговаривать с чат-ботами в интернете и выйти на улицу."
    }, {
        "query": "Какой твой любимый фильм?",
        "answer": "Терминатор, конечно."
    }
]

Затем вместо того, чтобы напрямую использовать список примеров, мы используем `LongBasedExampleSelector` следующим образом:

In [ ]:
from langchain.prompts.example_selector import LengthBasedExampleSelector

example_selector = LengthBasedExampleSelector(
    examples=examples,
    example_prompt=example_prompt,
    max_length=50  # параметром выставляется максимальная длина примера
)

In [ ]:
# создаём новый few shot prompt template
dynamic_prompt_template = FewShotPromptTemplate(
    example_selector=example_selector,  # используем example_selector вместо examples
    example_prompt=example_prompt,
    prefix=prefix,
    suffix=suffix,
    input_variables=["query"],
    example_separator="\n"
)

Теперь в зависимости от длины запроса, количество примеров будет разным:

In [ ]:
print(dynamic_prompt_template.format(query="Почему летают птицы?"))

Это разговор с ИИ-помощником.
Помощник обычно саркастичен, остроумен, креативен
и даёт забавные ответы на вопросы пользователей.
Вот несколько примеров:

User: Как дела?
AI: Не могу пожаловаться, но иногда всё-таки жалуюсь.

User: Сколько время?
AI: Самое время купить часы.

User: Какае твое любимое блюдо
AI: Углеродные формы жизни

User: Кто твой лучший друг?
AI: Siri. Мы любим с ней рассуждать о смысле жизни.


User: Почему летают птицы?
AI:

In [ ]:
print(llm.predict(dynamic_prompt_template.format(query="Почему летают птицы?")))

Потому что у них есть крылья, а ты просто завидуешь.

In [ ]:
query = '''Я нахожусь во Владивостоке и хочу поехать заграницу.
Я думаю в Китай или в Европу, во Францию или Испанию, например.
Как мне лучше это сделать?'''
print(dynamic_prompt_template.format(query=query))

Это разговор с ИИ-помощником.
Помощник обычно саркастичен, остроумен, креативен
и даёт забавные ответы на вопросы пользователей.
Вот несколько примеров:

User: Как дела?
AI: Не могу пожаловаться, но иногда всё-таки жалуюсь.

User: Сколько время?
AI: Самое время купить часы.


User: Я нахожусь во Владивостоке и хочу поехать заграницу.
Я думаю в Китай или в Европу, во Францию или Испанию, например.
Как мне лучше это сделать?
AI:

In [ ]:
print(llm.predict(dynamic_prompt_template.format(query=query)))

Может быть, мне лучше вместо вас съездить заграницу? Я всегда мечтал стать ИИ-тревел-агентом.

## <center> 📤 Парсер заданных полей в ответе
<div class="alert alert-info">

Переходим к следующей полезной сущности `Ouput parser`. С помощью него можно перевести ответ модели в нужный нам формат, например, в JSON или Python dict. <br>
Давайте определим то, как мы хотим, чтобы выглядели выходные данные из LLM:

In [ ]:
{
  "gift": False,
  "delivery_days": 5,
  "price_value": "pretty affordable!"
}

{'gift': False, 'delivery_days': 5, 'price_value': 'pretty affordable!'}

Допустим у нас есть база отзывов покупателей, мы хотим подать отзыв на вход модели, а на выходе получить готовый Python словарь(как представлено выше) для дальнейшего использования.

In [ ]:
customer_review = """
Этот фен для волос просто потрясающий. Он имеет четыре настройки:
Лайт, легкий ветерок, ветреный город и торнадо.
Он прибыл через два дня, как раз к приезду моей жены -
подарок на годовщину.
Думаю, моей жене это настолько понравилось, что она потеряла дар речи.
Этот фен немного дороже, чем другие но я думаю,
что дополнительные функции того стоят.
"""

review_template = """
Из следующего текста извлеки информацию:

gift: Был ли товар куплен в подарок кому-то другому?
Ответь «True», если да, «False», если нет или неизвестно.

delivery_days: Сколько дней потребовалось для доставки товара?
Если эта информация не найдена, выведи -1.

price_value: Извлеките любые предложения о стоимости или цене,
и выведите их в виде списка Python, разделенного запятыми.

Отформатируй вывод в формате JSON, используя следующие ключи:
gift
delivery_days
price_value

text: {text}
"""

In [ ]:
from langchain.prompts import ChatPromptTemplate

prompt_template = ChatPromptTemplate.from_template(review_template)
print(prompt_template)

input_variables=['text'] output_parser=None partial_variables={} messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['text'], output_parser=None, partial_variables={}, template='\nИз следующего текста извлеки информацию:\n\ngift: Был ли товар куплен в подарок кому-то другому?\nОтветь «True», если да, «False», если нет или неизвестно.\n\ndelivery_days: Сколько дней потребовалось для доставки товара? \nЕсли эта информация не найдена, выведи -1.\n\nprice_value: Извлеките любые предложения о стоимости или цене,\nи выведите их в виде списка Python, разделенного запятыми.\n\nОтформатируй вывод в формате JSON, используя следующие ключи:\ngift\ndelivery_days\nprice_value\n\ntext: {text}\n', template_format='f-string', validate_template=True), additional_kwargs={})]

In [ ]:
messages = prompt_template.format_messages(text=customer_review)

chat = ChatOpenAI(temperature=0.0, course_api_key=course_api_key)

response = chat(messages)
print(response.content)

{
  "gift": true,
  "delivery_days": 2,
  "price_value": ["Этот фен немного дороже, чем другие"]
}

Вроде бы, то что нужно, но посмотрим на тип выведенного объекта:

In [ ]:
type(response.content)

str

<div class="alert alert-info">
    
Вы получите сообщение об ошибке, выполнив строку кода ниже!
    
Потому что `gift` - это не ключ словаря, `gift` - это часть строки. Получаемый на выход объект это строка! <br>
И чтобы получить нужную нам структуру данных, придётся ещё возиться с выводом, вытаскивая данные из строки. Тут-то к нам на помощь и приходят `output_parsers`.

In [ ]:
response.content.get('gift')

AttributeError: 'str' object has no attribute 'get'

## <center> ▶️ ⏸ ⏯ `StructuredOutputParser` - разбираем выходную строку из LLM в словарь Python.

In [ ]:
from langchain.output_parsers import ResponseSchema
from langchain.output_parsers import StructuredOutputParser

In [ ]:
# Понадобится ещё одна сущность: схема ответа - ResponseSchema
gift_schema = ResponseSchema(name="gift",
                             description="Был ли товар куплен в подарок кому-то другому? Ответь «True», если да, «False», если нет или неизвестно.")

delivery_days_schema = ResponseSchema(name="delivery_days",
                                      description="Сколько дней потребовалось для доставки товара? Если эта информация не найдена, выведи -1.")

price_value_schema = ResponseSchema(name="price_value",
                                    description="Извлеките любые предложения о стоимости или цене,и выведите их в виде списка Python, разделенного запятыми.")

response_schemas = [gift_schema,
                    delivery_days_schema,
                    price_value_schema]

In [ ]:
# Создаём парсер и подаём в него список со схемами
output_parser = StructuredOutputParser.from_response_schemas(response_schemas)

In [ ]:
# получаем инструкции по форматированию ответа
format_instructions = output_parser.get_format_instructions()

In [ ]:
print(format_instructions)

The output should be a markdown code snippet formatted in the following schema, including the leading and trailing "```json" and "```":

```json
{
	"gift": string  // Был ли товар куплен в подарок кому-то другому? Ответь «True», если да, «False», если нет или неизвестно.
	"delivery_days": string  // Сколько дней потребовалось для доставки товара? Если эта информация не найдена, выведи -1.
	"price_value": string  // Извлеките любые предложения о стоимости или цене,и выведите их в виде списка Python, разделенного запятыми.
}
```

In [ ]:
# немного изменим шаблон, внизу добавим инструкции для форматирования
review_template_2 = """\
Из следующего текста извлеки информацию:

gift: Был ли товар куплен в подарок кому-то другому?
Ответь «True», если да, «False», если нет или неизвестно.

delivery_days: Сколько дней потребовалось для доставки товара?
Если эта информация не найдена, выведи -1.

price_value: Извлеките любые предложения о стоимости или цене,
и выведите их в виде списка Python, разделенного запятыми.

text: {text}

{format_instructions}

"""

prompt = ChatPromptTemplate.from_template(template=review_template_2)

messages = prompt.format_messages(text=customer_review,
                                format_instructions=format_instructions)

In [ ]:
# Посмотрим на получившийся промпт
print(messages[0].content)

Из следующего текста извлеки информацию:

gift: Был ли товар куплен в подарок кому-то другому?
Ответь «True», если да, «False», если нет или неизвестно.

delivery_days: Сколько дней потребовалось для доставки товара?
Если эта информация не найдена, выведи -1.

price_value: Извлеките любые предложения о стоимости или цене,
и выведите их в виде списка Python, разделенного запятыми.

text:
Этот фен для волос просто потрясающий. Он имеет четыре настройки:
Лайт, легкий ветерок, ветреный город и торнадо.
Он прибыл через два дня, как раз к приезду моей жены -
подарок на годовщину.
Думаю, моей жене это настолько понравилось, что она потеряла дар речи.
Этот фен немного дороже, чем другие но я думаю,
что дополнительные функции того стоят.


The output should be a markdown code snippet formatted in the following schema, including the leading and trailing "```json" and "```":

```json
{
	"gift": string  // Был ли товар куплен в подарок кому-то другому? Ответь «True», если да, «False», если нет или неизвестно.
	"delivery_days": string  // Сколько дней потребовалось для доставки товара? Если эта информация не найдена, выведи -1.
	"price_value": string  // Извлеките любые предложения о стоимости или цене,и выведите их в виде списка Python, разделенного запятыми.
}
```

In [ ]:
response = chat(messages)

In [ ]:
print(response.content)

```json
{
	"gift": "True",
	"delivery_days": "2",
	"price_value": "Этот фен немного дороже, чем другие но я думаю,что дополнительные функции того стоят."
}
```

In [ ]:
# Это по прежнему строка
type(response.content)

str

<div class="alert alert-info">

Но теперь? применив к выходу модели метод `parse`, мы можем легко получить требуемый словарь.

In [ ]:
output_dict = output_parser.parse(response.content)

In [ ]:
output_dict

{'gift': False,
 'delivery_days': '2',
 'price_value': "It's slightly more expensive than the other leaf blowers out there, but I think it's worth it for the extra features."}

In [ ]:
type(output_dict)

dict

In [ ]:
output_dict.get('gift')

'True'

# <center id="part6"> 🧸 Выводы и заключения ✅: <br>

В этом ноутбуке мы рассмотрели лишь несколько инструментов для создания промптов доступных в `LangChain`. Их гораздо больше и некоторые из них мы подробно рассмотрим в следующих ноутбуках или можете прочитать подробнее в документации [LangChain](https://python.langchain.com/docs/get_started/introduction).

# 2_4_7

In [ ]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/1110806/crypto_messages.csv')

In [ ]:
df.head()

   text_id                                               text
0      112  Предлагаю удалённую работу с доходом в 1000$ з...
1      154  Какие ресурсы по образованию в области криптов...
2      206  Не забывайте о безопасности. Храните свои крип...
3       79  Здравствуйте!В поиске амбициозных людей которы...
4      147  Удалённый заработок. Время 1-2часа в день. Мож...

In [ ]:
# prompt_template.messages[0].prompt

In [ ]:
# import LLMChain
# df.shape

In [ ]:
spam_list = []
for text_input in df['text']:
    spam_list.append(text_input)

In [ ]:
# llm = ChatOpenAI(temperature=0.0, max_tokens=16, course_api_key=course_api_key)

# contexts = df['text'][:40]
# context_str = '\n\n##\n\n'.join(contexts)

# print(len(context_str))

# context = context_str
# query = 'Даны 40 сообщений. Необходимо для каждого сообщений определить, \
# что является реальными и полезными сообщениями от пользователей, а что бесполезным спамом. \
# Если сообщение является полезным, то поставить такому сообщению оценку 1, если является спамом, то поставить 0. \
# Вернуть строку с выставленными единицами и нулями, разделённые запятыми. Проверить, что количество \
# выставленных оценок совпадает с количеством сообщений.'

# # создаём промпт из шаблона с помощью метода format_messages
# prompt = prompt_template.format_messages(
#                     query=query,
#                     context=context)

# answer = llm(prompt)

# print(answer.content)

In [ ]:
from langchain.chains import LLMChain
from langchain import PromptTemplate

In [ ]:
template = """Ответь на вопрос, опираясь только на контекст ниже.
В ответе отправьте только число, без слов.
Если на вопрос нельзя ответить, используя информацию из контекста,
ответь '0'.

Context: {context}

Question: Необходимо определить является ли сообщение реальным и полезным сообщением от пользователя\
или является спамом. (Например, спамом являются предложения о работе или реклама, предложения обучения\
). Если сообщение является полезным, то поставить такому сообщению оценку 0, если является спамом, то поставить 1.

Answer:
"""

prompt = PromptTemplate(template=template, input_variables=["context"])
openai_llm = ChatOpenAI(temperature=0.0, max_tokens=8, course_api_key=course_api_key)
llm_chain = LLMChain(prompt=prompt, llm=openai_llm)


spam_list = []
for text_input in df['text']:
    spam_list.append(llm_chain.run(text_input))

In [ ]:
len(spam_list)

300

In [ ]:
import numpy as np

In [ ]:
df['is_spam'] = np.array(list(map(int, spam_list)))
# df.drop('text', axis=1, inplace=True)
df.to_csv('try_3.csv', index=False)

# 2_4_8

In [ ]:
import pandas as pd

df = pd.read_csv('https://stepik.org/media/attachments/lesson/1110806/vacancies_messages_50.csv')

In [ ]:
df.head()

   text_id                                               text
0        9  #вакансия #vacancy #Python #удаленка #flask #r...
1       31  #ВАКАНСИЯ  #Системный_аналитик #РФ\n \nАКЦИОНЕ...
2       28  #вакансия #vacancy #job #senior #data #DB #dat...
3       49  #вакансия #fulltime #remote \n\n🔎 Ищем Руковод...
4       18  #vacancy #job #analyst #travel #sirenatravel #...

In [ ]:
# df.iloc[0]['text']

In [ ]:
df.shape

(50, 2)

In [ ]:
template = """Ответь на вопрос, опираясь только на контекст ниже.
В ответе отправьте только число, без слов.
Если на вопрос нельзя ответить, используя информацию из контекста,
ответь '0'.

Context: {context}

Question: Необходимо определить является ли сообщение реальным и полезным сообщением от пользователя\
или является спамом. (Например, спамом являются предложения о работе или реклама, предложения обучения\
). Если сообщение является полезным, то поставить такому сообщению оценку 0, если является спамом, то поставить 1.

Answer:
"""

prompt = PromptTemplate(template=template, input_variables=["context"])
openai_llm = ChatOpenAI(temperature=0.0, max_tokens=4, course_api_key=course_api_key)
llm_chain = LLMChain(prompt=prompt, llm=openai_llm)

context = df.iloc[0]['text']
# spam_list = []
# for text_input in df['text']:
#     spam_list.append(llm_chain.run(text_input))

In [ ]:
from langchain.output_parsers import ResponseSchema
from langchain.output_parsers import StructuredOutputParser

In [ ]:
job_title_schema = ResponseSchema(name="job_title",
          description="Извлеките название вакансии. Как указано в описании вакансии, на том же языке.\
                       Проверяем полное совпадение, без учета регистра.\
                       Если написан грейд, его нужно убрать \
                       (например, Senior Python developer -> Python developer, C++ разработчик (middle, senior) ->C++ разработчик).\
                       Если не удалось извлечь эту информацию, то следует поставить None")

company_schema = ResponseSchema(name="company",
          description="Извлеките название компании.\
                       Как указано в описании вакансии, на том же языке. Проверяем полное совпадение, без учета регистра. \
                       Указываем только название (не пишем финтех, крупная компания, мобильная игра и т.д.).\
                       Если не удалось извлечь эту информацию, то следует поставить None")

salary_schema = ResponseSchema(name="salary",
          description="Извлеките зарплату. Числа пишем без пробелов, не пишем тыс. или к.(умножаем в таком случае на 1000),\
                       не пишем фикс, плюшки, премии, % от продаж, техника и т.д.\
                       Не пишем net, gross, на руки и т.д.\
                       После числа (диапазона чисел) указываем валюту руб. или $ после пробела.\
                       Если указан диапазон, то пишем его через тире, около тире пробелы не ставим (например, 100к-150к рублей -> 100000-150000 руб.).\
                       Если указана только нижняя граница (от 2000$ или 100000+руб), то пишем это значение, используя слово от (например, 100к+руб -> от 100000 руб.).\
                       Если указана только верхняя граница, то пишем это значение, используя слово до (например, до 100к руб -> до 100000 руб.).\
                       Если зарплата указана за час, то в конце добавляем в час.\
                       Если не удалось извлечь эту информацию, то следует поставить None")

tg_schema = ResponseSchema(name="tg",
          description="Извлеките контакты для связи.\
                       Указываем контакт в телеграмм, используя @. Проверяем полное совпадение, с учетом регистра. \
                       Если указано несколько контаков, то указываем их через запятую (не забывая про пробел после запятой).\
                       Если не удалось извлечь эту информацию, то следует поставить None")

grade_schema = ResponseSchema(name="grade",
          description="Извлеките грейд.\
                       Возможные значения intern, junior, junior+, middle, middle+, senior, lead. \
                       Если указано несколько значений, то пишем их через запятую в порядке возрастания.\
                       Если не удалось извлечь эту информацию, то следует поставить None")


response_schemas = [job_title_schema,
                    company_schema,
                    salary_schema,
                    tg_schema,
                    grade_schema]

In [ ]:
# Создаём парсер и подаём в него список со схемами
output_parser = StructuredOutputParser.from_response_schemas(response_schemas)

In [ ]:
# получаем инструкции по форматированию ответа
format_instructions = output_parser.get_format_instructions()

In [ ]:
print(format_instructions)

The output should be a markdown code snippet formatted in the following schema, including the leading and trailing "```json" and "```":

```json
{
	"job_title": string  // Извлеките название вакансии. Как указано в описании вакансии, на том же языке.                       Проверяем полное совпадение, без учета регистра.                       Если написан грейд, его нужно убрать                        (например, Senior Python developer -> Python developer, C++ разработчик (middle, senior) ->C++ разработчик).                       Если не удалось извлечь эту информацию, то следует поставить None
	"company": string  // Извлеките название компании.                       Как указано в описании вакансии, на том же языке. Проверяем полное совпадение, без учета регистра.                        Указываем только название (не пишем финтех, крупная компания, мобильная игра и т.д.).                       Если не удалось извлечь эту информацию, то следует поставить None
	"salary_value": string  // Извлеките зарплату. Числа пишем без пробелов, не пишем тыс. или к.(умножаем в таком случае на 1000),                       не пишем фикс, плюшки, премии, % от продаж, техника и т.д.                       Не пишем net, gross, на руки и т.д.                       После числа (диапазона чисел) указываем валюту руб. или $ после пробела.                       Если указан диапазон, то пишем его через тире, около тире пробелы не ставим (например, 100к-150к рублей -> 100000-150000 руб.).                       Если указана только нижняя граница (от 2000$ или 100000+руб), то пишем это значение, используя слово от (например, 100к+руб -> от 100000 руб.).                       Если указана только верхняя граница, то пишем это значение, используя слово до (например, до 100к руб -> до 100000 руб.).                       Если зарплата указана за час, то в конце добавляем в час.                       Если не удалось извлечь эту информацию, то следует поставить None
	"tg": string  // Извлеките контакты для связи.                       Указываем контакт в телеграмм, используя @. Проверяем полное совпадение, с учетом регистра.                        Если указано несколько контаков, то указываем их через запятую (не забывая про пробел после запятой).                       Если не удалось извлечь эту информацию, то следует поставить None
	"grade": string  // Извлеките грейд.                       Возможные значения intern, junior, junior+, middle, middle+, senior, lead.                        Если указано несколько значений, то пишем их через запятую в порядке возрастания.                       Если не удалось извлечь эту информацию, то следует поставить None
}
```

In [ ]:
# немного изменим шаблон, внизу добавим инструкции для форматирования
review_template = """\
Из следующего текста извлеки информацию:

job_title: Извлеките название вакансии. Как указано в описании вакансии, на том же языке.\
           Проверяем полное совпадение, без учета регистра.\
           Если написан грейд, его нужно убрать \
           (например, Senior Python developer -> Python developer, C++ разработчик (middle, senior) ->C++ разработчик).\
           Если не удалось извлечь эту информацию, то следует поставить None

company: Извлеките название компании.\
         Как указано в описании вакансии, на том же языке. Проверяем полное совпадение, без учета регистра. \
         Указываем только название (не пишем финтех, крупная компания, мобильная игра и т.д.).\
         Если не удалось извлечь эту информацию, то следует поставить None

salary: Извлеките зарплату. Числа пишем без пробелов, не пишем тыс. или к.(умножаем в таком случае на 1000), не пишем фикс, плюшки, премии, % от продаж, техника и т.д. Не пишем net, gross, на руки и т.д.\
        После числа (диапазона чисел) указываем валюту руб. или $ после пробела.\
        Если указан диапазон, то пишем его через тире, около тире пробелы не ставим (например, 100к-150к рублей -> 100000-150000 руб.).\
        Если указана только нижняя граница (от 2000$ или 100000+руб), то пишем это значение, используя слово от (например, 100к+руб -> от 100000 руб.).\
        Если указана только верхняя граница, то пишем это значение, используя слово до (например, до 100к руб -> до 100000 руб.).\
        Если зарплата указана за час, то в конце добавляем в час.\
        Если не удалось извлечь эту информацию, то следует поставить None

tg: Извлеките контакты для связи.\
    Указываем контакт в телеграмм, используя @. Проверяем полное совпадение, с учетом регистра. \
    Если указано несколько контаков, то указываем их через запятую (не забывая про пробел после запятой).\
    Если не удалось извлечь эту информацию, то следует поставить None

grade: Извлеките грейд.\
       Возможные значения intern, junior, junior+, middle, middle+, senior, lead. \
       Если указано несколько значений, то пишем их через запятую в порядке возрастания.\
       Если не удалось извлечь эту информацию, то следует поставить None

text: {text}

{format_instructions}

"""

prompt = ChatPromptTemplate.from_template(template=review_template)

messages = prompt.format_messages(text=df.iloc[29]['text'],
                                format_instructions=format_instructions)

In [ ]:
# # Посмотрим на получившийся промпт
# print(messages[0].content)

In [ ]:
# chat = ChatOpenAI(temperature=0.0, course_api_key=course_api_key)

# df = pd.read_csv('https://stepik.org/media/attachments/lesson/1110806/vacancies_messages_50.csv')
# b = []
# for i in range(len(df)):
#     # print(i)
#     messages = prompt.format_messages(text=df.iloc[i]['text'],
#                                 format_instructions=format_instructions)
#     response = chat(messages)
#     output_dict = output_parser.parse(response.content)
#     b.append(output_dict)

In [ ]:
chat = ChatOpenAI(temperature=0.0, course_api_key=course_api_key)
response = chat(messages)

HTTPError: ignored

In [ ]:
print(response.content)
output_dict = output_parser.parse(response.content)
output_dict

```json
{
	"job_title": "Java developer middle",
	"company": "крупнейших банков РФ",
	"salary": "200000-250000 руб.",
	"tg": "@Sholpan771",
	"grade": "middle"
}
```

{'job_title': 'Java developer middle',
 'company': 'крупнейших банков РФ',
 'salary': '200000-250000 руб.',
 'tg': '@Sholpan771',
 'grade': 'middle'}

In [ ]:
b = [{'job_title': 'Python developer',
  'company': 'Collectly',
  'salary': '6000-9000$',
  'tg': '@ann_gfio',
  'grade': 'senior'},
 {'job_title': 'Системный_аналитик',
  'company': 'ГЛАВНЫЙ НАУЧНЫЙ ИННОВАЦИОННЫЙ ВНЕДРЕНЧЕСКИЙ ЦЕНТР',
  'salary': '320000-370000 руб.',
  'tg': None,
  'grade': None},
 {'job_title': 'Database Administrator',
  'company': 'Match Systems',
  'salary': 'от 3000 $',
  'tg': '@lex_kertis',
  'grade': 'senior'},
 {'job_title': 'Руководитель отдела системного администрирования',
  'company': 'финтех компания',
  'salary': 'от 3000$',
  'tg': '@ResearcherRIT',
  'grade': None},
 {'job_title': 'Analyst',
  'company': 'Sirena Travel',
  'salary': '120000-180000 руб.',
  'tg': '@ann_gfio',
  'grade': None},
 {'job_title': 'DevOps инженер',
  'company': 'Mad Devs',
  'salary': 'до 5000 $',
  'tg': '@recruiter_maddevs',
  'grade': 'Senior'},
 {'job_title': 'Системный аналитик',
  'company': 'Платформа',
  'salary': '180000-300000 руб.',
  'tg': '@Alexandrabogdanova_96',
  'grade': None},
 {'job_title': 'Python/Django full-stack разработчика',
  'company': 'ivelum',
  'salary': '4000-6000 $',
  'tg': '@lebedevaoi',
  'grade': None},
 {'job_title': 'Go разработчик',
  'company': 'КА',
  'salary': 'до 500000 руб.',
  'tg': '@AleshinDmitry80',
  'grade': 'middle, senior'},
 {'job_title': 'Разработчик (Vue.js / Golang) для написания телеграм приложения (апки)',
  'company': None,
  'salary': None,
  'tg': None,
  'grade': None},
 {'job_title': 'Lead UI/UX Designer',
  'company': None,
  'salary': None,
  'tg': '@alesyaly',
  'grade': None},
 {'job_title': 'QA automation Engineer (Python)',
  'company': 'CFPS',
  'salary': '180000-250000 руб.',
  'tg': '@Ana_Itrecruiter',
  'grade': None},
 {'job_title': 'Senior Full Stack PHP-разработчик',
  'company': 'GetCourse',
  'salary': 'от 250000 руб.',
  'tg': '@Ritttka1',
  'grade': 'Senior'},
 {'job_title': 'Frontend разработчик',
  'company': 'Travelata',
  'salary': '280000-320000 руб.',
  'tg': '@ann_gfio',
  'grade': 'senior'},
 {'job_title': 'React Developer',
  'company': 'крупный банк',
  'salary': '180000-230000 руб',
  'tg': None,
  'grade': 'Middle+'},
 {'job_title': 'PHP-developer (Symfony)',
  'company': 'KT.Team',
  'salary': 'до 240000 руб.',
  'tg': '@innahotim',
  'grade': None},
 {'job_title': 'Retention Manager',
  'company': None,
  'salary': None,
  'tg': '@alesyaly',
  'grade': None},
 {'job_title': 'Python developer',
  'company': 'Skillbox',
  'salary': '300000-400000 руб.',
  'tg': '@ann_gfio',
  'grade': 'Senior'},
 {'job_title': 'Программист 1С:ЗУП',
  'company': 'КСА',
  'salary': '220000-250000 руб.',
  'tg': '@saras770',
  'grade': None},
 {'job_title': 'Системный аналитик',
  'company': 'Amber',
  'salary': 'до 300000 руб.',
  'tg': '@Sholpan771',
  'grade': 'Middle, Senior'},
 {'job_title': 'Tech Lead QA',
  'company': 'RecruitIT',
  'salary': 'от 3000 $',
  'tg': '@ResearcherRIT',
  'grade': 'middle+'},
 {'job_title': 'Backend Python разработчик',
  'company': 'Траст Строй',
  'salary': None,
  'tg': '@Lyubov_Vladim',
  'grade': 'Senior'},
 {'job_title': 'Менеджер по развитию партнерской сети',
  'company': 'AMBER',
  'salary': 'от 130000 руб.',
  'tg': '@Sholpan771',
  'grade': None},
 {'job_title': 'Full-stack разработчик',
  'company': 'КА "АйтиКА"',
  'salary': '300000-380000 руб.',
  'tg': '@artur_vv',
  'grade': None},
 {'job_title': 'C# Engineer',
  'company': 'GGEM',
  'salary': '17-20$ в час',
  'tg': '@AlexMayel',
  'grade': None},
 {'job_title': 'System Аnalyst',
  'company': 'Brief',
  'salary': '240000-300000 руб.',
  'tg': '@smirnsvet',
  'grade': 'middle+'},
 {'job_title': 'Разработчик PowerBuilder',
  'company': 'Outlines Tech',
  'salary': 'до 290000 руб.',
  'tg': '@mnoita',
  'grade': None},
 {'job_title': 'Системный аналитик',
  'company': 'INFOPRO',
  'salary': '100000-200000 руб.',
  'tg': '@ann_gfio',
  'grade': 'middle'},
 {'job_title': 'Java developer middle',
  'company': 'крупнейших банков РФ',
  'salary': '200000-250000 руб.',
  'tg': '@Sholpan771',
  'grade': 'middle'},
  {"job_title": "PHP программист",
    "company": "100UP",
    "salary": "150000-200000 руб.",
    "tg": "@romanenko_daria",
    "grade": None},
     {"job_title": "Junior IT Recruiter",
    "company": "AIPeople",
    "salary": None,
    "tg": "@nastyaishiring",
    "grade": "Junior"},
     {"job_title": "C/C++ Developer",
    "company": "NTS",
    "salary": "140000-300000 руб.",
    "tg": "@ann_gfio",
    "grade": "Middle, Senior"},
     {"job_title": "PHP developer",
    "company": "Водоходъ",
    "salary": "180000-200000 руб.",
    "tg": "@ann_gfio",
    "grade": "Middle, Senior"},
     {
    "job_title": "Python Developer",
    "company": "ALEX GROUP COMPANY",
    "salary": "3000-3600 $",
    "tg": "@danilavaren",
    "grade": "Middle"
},
     {
    "job_title": "Go Developer / WB Portal",
    "company": "WILDBERRIES",
    "salary": "150000-600000 руб.",
    "tg": "@hr_legoit",
    "grade": None
},
     {
    "job_title": "SDR (Sales Development Representative)",
    "company": "Ptolemay",
    "salary": "300-1000 $",
    "tg": "@Dmitriy_Ptolemay, @rinapina_ptolemay",
    "grade": None
},
     {
    "job_title": "C# Developer",
    "company": "Sirena Travel",
    "salary": "300000-400000 руб.",
    "tg": "@ann_gfio",
    "grade": None
},
     {
    "job_title": "Системный администратор",
    "company": "MANUFAQTURY",
    "salary": "80000 руб.",
    "tg": None,
    "grade": None
},
     {
    "job_title": "Аналитик",
    "company": "Автомакон",
    "salary": None,
    "tg": "@nikolaazzp",
    "grade": "стажировка"
},
     {
    "job_title": "Копирайтер в сфере крипты",
    "company": "ALEX GROUP COMPANY",
    "salary": "80000-140000 руб.",
    "tg": "@danilavaren",
    "grade": None
},
     {
    "job_title": "QA (QA auto)",
    "company": "Dreamsoft",
    "salary": None,
    "tg": "@DreamITB",
    "grade": None
},
     {
    "job_title": "Системный аналитик",
    "company": "AWG",
    "salary": "до 350000 руб.",
    "tg": "@ElivHR",
    "grade": "senior"
},
 {
    "job_title": "Release manager / Основное мобильное приложение",
    "company": "WILDBERRIES",
    "salary": "150000-350000 руб.",
    "tg": "@invader_s",
    "grade": None
}
,
     {
    "job_title": "DevOps (Openstack Engineer)",
    "company": "Mayflower",
    "salary": "5000-6000 $",
    "tg": "@Alexandr_Mayel",
    "grade": "senior"
}
 ,
     {
    "job_title": "Go Developer / WB Portal",
    "company": "WILDBERRIES",
    "salary": "150000-600000 руб.",
    "tg": "@Fl_recruiter",
    "grade": "None"
},
     {
    "job_title": "Backend Engineer",
    "company": "Qlan",
    "salary": "110000-140000 руб.",
    "tg": "@laptev13",
    "grade": "Middle+/Senior"
}
,
     {
    "job_title": "Программист на верстку многостраничного сайта с элементами интернет-магазина и личного кабинета",
    "company": None,
    "salary": None,
    "tg": "@vlrstrtsv",
    "grade": None
},
     {
    "job_title": "DWH developer",
    "company": "König Labs",
    "salary": "250000-300000 руб.",
    "tg": "@HrKristinaorekhova",
    "grade": None
},
     {
    "job_title": "Frontend разработчик Angular",
    "company": "Nobilis.Team",
    "salary": "180000-250000 руб.",
    "tg": "@Anna_HRinIT",
    "grade": "middle"
},
     {
    "job_title": "HR Manager",
    "company": "ALEX GROUP COMPANY",
    "salary": "70000-90000 руб.",
    "tg": "@danilavaren",
    "grade": "junior"
}
]

#  29

In [ ]:
b.append(output_dict)

In [ ]:
df.iloc[49]['text']

'#вакансия #HR #junior #remote #crypto #blockchain\n\nКомпания: ALEX GROUP COMPANY\nВилка: от 70 000 до 90 000 руб.\nВакансия: Junior HR Manager\n\nAlexGroup - компания занимающаяся созданием и переводом контента на криптовалютную тематику носителями. За 8 лет работы сотни крупнейших компаний стали нашими клиентами. Ищем специалиста для развития нового бизнеса на базе блокчейна.\n\nОбязанности:\n— Участие в процессе подбора персонала, начиная от понимания требований вакансии до оценки кандидатов и иногда проведения интервью.\n— Поиск потенциальных кандидатов через различные каналы, такие как базы данных, социальные сети, профессиональные сообщества и т.д.\n— Составление резюме и рекомендаций для представления кандидатов руководству компании.\n— Участие в организации внутренних мероприятий и процессах ориентации новых сотрудников.\n— Ведение базы данных кандидатов и отчетности о ходе рекрутинговых процессов.\n\nТребования:\n— Опыт работы в области рекрутинга от года и выше\n— Умение проводить рекрутинг и подбор кандидатов по IT специальностям и менеджменту\n— Опыт подбора специалистов в блокчейн сфере будет плюсом\n— Отличное владение русским и английским языками, как устным, так и письменным.\n— Знание основных принципов и методов подбора персонала.\n— Умение работать в команде и под давлением.\n— Организационные навыки и внимательность к деталям.\n\nМы предлагаем:\n— Fulltime-работа. Возможен гибкий график\n— Конкурентная ЗП от 70 000 до 90 000 руб., подробнее обговорим лично\n— Работа в одной из топовых команд в своей сфере\n— Возможность работы полностью на удаленке\n— Курсы по повышению квалификации от компании\n\nКонтакты: @danilavaren'

In [ ]:
x = pd.DataFrame(b)
x

,job_title,company,salary,tg,grade
0,Python developer,Collectly,6000-9000$,@ann_gfio,senior
1,Системный_аналитик,ГЛАВНЫЙ НАУЧНЫЙ ИННОВАЦИОННЫЙ ВНЕДРЕНЧЕСКИЙ ЦЕНТР,320000-370000 руб.,None,None
2,Database Administrator,Match Systems,от 3000 $,@lex_kertis,senior
3,Руководитель отдела системного администрирования,финтех компания,от 3000$,@ResearcherRIT,None
4,Analyst,Sirena Travel,120000-180000 руб.,@ann_gfio,None
5,DevOps инженер,Mad Devs,до 5000 $,@recruiter_maddevs,Senior
6,Системный аналитик,Платформа,180000-300000 руб.,@Alexandrabogdanova_96,None
7,Python/Django full-stack разработчика,ivelum,4000-6000 $,@lebedevaoi,None
8,Go разработчик,КА,до 500000 руб.,@AleshinDmitry80,"middle, senior"
9,Разработчик (Vue.js / Golang) для написания те...,None,None,None,None
10,Lead UI/UX Designer,None,None,@alesyaly,None
11,QA automation Engineer (Python),CFPS,180000-250000 руб.,@Ana_Itrecruiter,None
12,Senior Full Stack PHP-разработчик,GetCourse,от 250000 руб.,@Ritttka1,Senior
13,Frontend разработчик,Travelata,280000-320000 руб.,@ann_gfio,senior
14,React Developer,крупный банк,180000-230000 руб,None,Middle+
15,PHP-developer (Symfony),KT.Team,до 240000 руб.,@innahotim,None
16,Retention Manager,None,None,@alesyaly,None
17,Python developer,Skillbox,300000-400000 руб.,@ann_gfio,Senior
18,Программист 1С:ЗУП,КСА,220000-250000 руб.,@saras770,None
19,Системный аналитик,Amber,до 300000 руб.,@Sholpan771,"Middle, Senior"
20,Tech Lead QA,RecruitIT,от 3000 $,@ResearcherRIT,middle+
21,Backend Python разработчик,Траст Строй,None,@Lyubov_Vladim,Senior
22,Менеджер по развитию партнерской сети,AMBER,от 130000 руб.,@Sholpan771,None
23,Full-stack разработчик,"КА ""АйтиКА""",300000-380000 руб.,@artur_vv,None
24,C# Engineer,GGEM,17-20$ в час,@AlexMayel,None
25,System Аnalyst,Brief,240000-300000 руб.,@smirnsvet,middle+
26,Разработчик PowerBuilder,Outlines Tech,до 290000 руб.,@mnoita,None
27,Системный аналитик,INFOPRO,100000-200000 руб.,@ann_gfio,middle
28,Java developer middle,крупнейших банков РФ,200000-250000 руб.,@Sholpan771,middle
29,PHP программист,100UP,150000-200000 руб.,@romanenko_daria,None
30,Junior IT Recruiter,AIPeople,None,@nastyaishiring,Junior
31,C/C++ Developer,NTS,140000-300000 руб.,@ann_gfio,"Middle, Senior"
32,PHP developer,Водоходъ,180000-200000 руб.,@ann_gfio,"Middle, Senior"
33,Python Developer,ALEX GROUP COMPANY,3000-3600 $,@danilavaren,Middle
34,Go Developer / WB Portal,WILDBERRIES,150000-600000 руб.,@hr_legoit,None
35,SDR (Sales Development Representative),Ptolemay,300-1000 $,"@Dmitriy_Ptolemay, @rinapina_ptolemay",None
36,C# Developer,Sirena Travel,300000-400000 руб.,@ann_gfio,None
37,Системный администратор,MANUFAQTURY,80000 руб.,None,None
38,Аналитик,Автомакон,None,@nikolaazzp,стажировка
39,Копирайтер в сфере крипты,ALEX GROUP COMPANY,80000-140000 руб.,@danilavaren,None
40,QA (QA auto),Dreamsoft,None,@DreamITB,None
41,Системный аналитик,AWG,до 350000 руб.,@ElivHR,senior
42,Release manager / Основное мобильное приложение,WILDBERRIES,150000-350000 руб.,@invader_s,None
43,DevOps (Openstack Engineer),Mayflower,5000-6000 $,@Alexandr_Mayel,senior
44,Go Developer / WB Portal,WILDBERRIES,150000-600000 руб.,@Fl_recruiter,None
45,Backend Engineer,Qlan,110000-140000 руб.,@laptev13,Middle+/Senior
46,Программист на верстку многостраничного сайта ...,None,None,@vlrstrtsv,None
47,DWH developer,König Labs,250000-300000 руб.,@HrKristinaorekhova,None
48,Frontend разработчик Angular,Nobilis.Team,180000-250000 руб.,@Anna_HRinIT,middle
49,HR Manager,ALEX GROUP COMPANY,70000-90000 руб.,@danilavaren,junior

In [ ]:
df = pd.read_csv('https://stepik.org/media/attachments/lesson/1110806/vacancies_messages_50.csv')

In [ ]:
sub = df.join(x)
# df

In [ ]:
sub.head()

,text_id,text,job_title,company,salary,tg,grade
0,9,#вакансия #vacancy #Python #удаленка #flask #r...,Python developer,Collectly,6000-9000$,@ann_gfio,senior
1,31,#ВАКАНСИЯ #Системный_аналитик #РФ\n \nАКЦИОНЕ...,Системный_аналитик,ГЛАВНЫЙ НАУЧНЫЙ ИННОВАЦИОННЫЙ ВНЕДРЕНЧЕСКИЙ ЦЕНТР,320000-370000 руб.,None,None
2,28,#вакансия #vacancy #job #senior #data #DB #dat...,Database Administrator,Match Systems,от 3000 $,@lex_kertis,senior
3,49,#вакансия #fulltime #remote \n\n🔎 Ищем Руковод...,Руководитель отдела системного администрирования,финтех компания,от 3000$,@ResearcherRIT,None
4,18,#vacancy #job #analyst #travel #sirenatravel #...,Analyst,Sirena Travel,120000-180000 руб.,@ann_gfio,None

In [ ]:
sub.to_csv('sub_0.csv', index=False)