<a href="https://colab.research.google.com/github/nedokormysh/Stepik_LLM/blob/week_2_prompting/LLM_2_1_%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D1%87.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install openai langchain tiktoken langchain-openai langchain-community -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 kB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 361.3/361.3 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 997.8/997.8 kB 11.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 32.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.8/49.8 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 41.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 318.9/318.9 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 384.8/384.8 kB 11.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 8.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.9/141.9 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 2.8 MB/s eta 0:00:00

## Если используете ключ от OpenAI, запустите эту ячейку 👇

In [ ]:
from langchain_openai import ChatOpenAI
import os
from getpass import getpass


# os.environ['OPENAI_API_KEY'] = "Введите ваш OpenAI API ключ"
os.environ['OPENAI_API_KEY'] = getpass(prompt='Введите ваш OpenAI API ключ')

# Инициализируем языковую модель
llm = ChatOpenAI(temperature=0.0)

## Если используете ключ из курса, запустите эти ячейки 👇

In [2]:
!wget https://raw.githubusercontent.com/a-milenkin/LLM_practical_course/main/notebooks/utils.py

--2024-08-13 09:10:57--  https://raw.githubusercontent.com/a-milenkin/LLM_practical_course/main/notebooks/utils.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11184 (11K) [text/plain]
Saving to: ‘utils.py’

utils.py            100%[===================>]  10.92K  --.-KB/s    in 0s

2024-08-13 09:10:57 (93.0 MB/s) - ‘utils.py’ saved [11184/11184]

In [3]:
from utils import ChatOpenAI
from getpass import getpass

#course_api_key= "Введите ваш API ключ с курса"
course_api_key = getpass(prompt='Введите API ключ')

# Инициализируем языковую модель
llm = ChatOpenAI(temperature=0.0, course_api_key=course_api_key)

Введите API ключ··········

## Задание 2.1.8 LLM — сила 💪, ML — могила 🧟

In [4]:
import pandas as pd
from tqdm import tqdm

In [5]:
df = pd.read_csv('https://stepik.org/media/attachments/lesson/1084297/submission100lines.csv')

In [6]:
df.head()

   amount    text_id                                               text
0       2   14205200  Сниму жилье. 500-600 рублей сутки. Эконом клас...
1       6  319097075  ищем жилье в центре недалеко от моря с 23.07-0...
2       4   98881311  Ищем жилье на период с 18-28июля..на две семьи...
3       4   44587027  2 семьи по 3 человека (2 взрослых и ребенок) с...
4       3  352802829  Сниму недорогое жилье в лазаревском на 6 чел 3...

In [7]:
df

    amount    text_id                                               text
0        2   14205200  Сниму жилье. 500-600 рублей сутки. Эконом клас...
1        6  319097075  ищем жилье в центре недалеко от моря с 23.07-0...
2        4   98881311  Ищем жилье на период с 18-28июля..на две семьи...
3        4   44587027  2 семьи по 3 человека (2 взрослых и ребенок) с...
4        3  352802829  Сниму недорогое жилье в лазаревском на 6 чел 3...
..     ...        ...                                                ...
95       4  233661411  Добрый день! Ищем жилье на 9 человек, 4 взросл...
96       1   77792435  Здравствуйте. Ищем жильё в период с 26 мая по ...
97       4  102311098  Добрый день! Ищем жилье в Лазаревском с 02.07-...
98       3  123993850  Ищем не дорогое жильё на начало июля , не дале...
99       2   54495881  ищем жилье с 8-20 августа с бассейном 3мест но...

[100 rows x 3 columns]

In [8]:
# Напишите шаблон промпт, указав инструкцию, вопрос и выходной индикатор

prompt_template = """Ответь на вопрос, опираясь на контекст ниже. В ответ напиши только цифру.

Context: {text_input}

Question: Сколько человек нуждается в жилье?

Answer: ...
"""

In [9]:
amount_list = [] # Список, где будем хранить ответы модели

for text_input in tqdm(df['text']):
    prompt = prompt_template.format(text_input=text_input) # Добавляем сообщение в промпт
    amount = llm.invoke(prompt).content # Ответ модели
    amount_list.append(amount) # Добавляем ответ в список
    break # Для отладки. Уберите, когда убедитесь, что на одном примере работает

  0%|          | 0/100 [00:00<?, ?it/s]

In [12]:
df['amount'] = amount_list # Создаём новый столбец из ответов модели

In [ ]:
df.to_csv('2_1_8_solution.csv', index=False) # Сохраняем файл, отправляем на Stepik, получаем баллы :)